### PR TITLE
fixed the wallet persistence

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Fixed the mobile wallet nav persistence

_before the wallet window on the mobile layout doesnt stay open for long

## It can be tested by:
by opening the wallet nav on the mobile phone / layout

1.How it was Before

https://user-images.githubusercontent.com/32770520/173316288-f1fd7ded-4489-4bd5-80dd-ec24c70779d0.mp4

2. How it is Now

https://user-images.githubusercontent.com/75235148/173779676-f2385ea7-4cde-49b8-b3ea-b01edff06207.mp4

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/425

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
image

@OleanjiKingCode, the wallet keeps loading. I think you should review the update you made to be sure you didn't break anything.

**Comment by kesar** [comment]
> image
> 
> @OleanjiKingCode, the wallet keeps loading. I think you should review the update you made to be sure you didn't break anything.

it seems to work fine to me, can you verify that error is this branch related? bcs I also don't see how the changes can affect to that part

**Comment by Emmanueldmlr** [comment]
@kesar, still having the same issue. I used this link: [https://monopedia-lixj4fkqx-prediqt.vercel.app/]

**Comment by kesar** [comment]
> @kesar, still having the same issue. I used this link: https://monopedia-lixj4fkqx-prediqt.vercel.app/

Have you tried in other .vercel.app PR to see if you face same issue? You also might need to provide how you are login and so on in order to the developer to understand the situation, but I feel this sounds unrelated to this issue

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
> > @kesar, still having the same issue. I used this link: https://monopedia-lixj4fkqx-prediqt.vercel.app/
> 
> Have you tried in other .vercel.app PR to see if you face same issue? You also might need to provide how you are login and so on in order to the developer to understand the situation, but I feel this sounds unrelated to this issue.
> 
> Lets make sure when we do a review in a PR we provide enough information and we don't block the PR for unrelated issues (not saying its 100% the case here, just as general thumbs rule reminder 👍🏻)

I get. It works well now. I don't know what went wrong.

**Comment by OleanjiKingCode** [comment]
> > > @kesar, still having the same issue. I used this link: https://monopedia-lixj4fkqx-prediqt.vercel.app/
> > 
> > 
> > Have you tried in other .vercel.app PR to see if you face same issue? You also might need to provide how you are login and so on in order to the developer to understand the situation, but I feel this sounds unrelated to this issue.
> > Lets make sure when we do a review in a PR we provide enough information and we don't block the PR for unrelated issues (not saying its 100% the case here, just as general thumbs rule reminder 👍🏻)
> 
> I get. It works well now. I don't know what went wrong.

is it okay to merge?

**Pull request merged**
