### PR TITLE
Fix glossary scroll issue

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# scroll issue on the Glossary page

we have to change the feature of searching while scrolling the page down to the letter. if a user types one letter and the search bar disappears. not a good experience.

## Linked issues
fixes https://github.com/EveripediaNetwork/issues/issues/890

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, let me know what you think about the implementation.

**Review by OleanjiKingCode — APPROVED** [review]

**Review by Simplypheyie96 — APPROVED** [review]
Awesome job. It works perfectly now

**Comment by Emmanueldmlr** [comment]
@OleanjiKingCode kindly work on the overflow issue @Royal-lobster talked about...let's make sure we merge this today.

**Comment by OleanjiKingCode** [comment]
@Emmanueldmlr  @Royal-lobster  can you check it now

**Comment by Royal-lobster** [comment]
> @Emmanueldmlr  @Royal-lobster  can you check it now
> 

Looks nice now !

**Comment by Emmanueldmlr** [comment]
Nice one @OleanjiKingCode ... weldone

**Comment by Emmanueldmlr** [comment]
@Softdev1, I guess we are good to go.

**Review by Softdev1 — APPROVED** [review]

**Comment by kesar** [comment]
letss goo :)

**Pull request merged**
