### PR TITLE
Further improvements to wiki details

### PR DESCRIPTION
**Pull request by SidharthK2**
# Further iterations to wiki details section
- Title repetition fix
- Uneven margins on actions bar
- typo fix

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2199

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- this is misaligned on medium breakpoint
image

**Comment by SidharthK2** [comment]
> * this is misaligned on medium breakpoint
>   image

Should be fixed

**Comment by Simplypheyie96** [comment]
@SidharthK2 
image
This is the design on figma for md breakpoint. maybe we can do that instead of the wide-margin they have on both sides 
figma link: https://www.figma.com/file/wosuJaHeV318k1ON82CZpo/%F0%9F%A7%A0-IQ.wiki?type=design&node-id=15206-107739&mode=design&t=c6p8Mub6sUjENr5L-11

**Review by Simplypheyie96 — APPROVED** [review]
Looks great

**Pull request merged**
