### PR TITLE
Fix MarketCap and Currency Converter Widget Issue

### PR DESCRIPTION
**Pull request by Aliiiu**
# MarketCap and Currency Converter Widget Issue

This PR works on resolving the issue with the marketcap and currency converter widget issue

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/

### CODE REVIEW

**Comment by Royal-lobster** [comment]
The issue linked and changes aren't matching 🤔 What does this PR supposed to do ?

**Review by Royal-lobster — APPROVED** [review]
Make sure to unlink the issue before merge

**Review by Softdev1 — APPROVED** [review]

**Comment by Aliiiu** [comment]
> The issue linked and changes aren't matching 🤔 What does this PR supposed to do ?



The issue was opened after the issue had been resolved so I just work on make it responsive

**Comment by Aliiiu** [comment]
> Make sure to unlink the issue before merge

Alright

**Pull request merged**
