### PR TITLE
Fixes toolbar icons overflow issue

### PR DESCRIPTION
**Pull request by Royal-lobster**
fixes https://github.com/EveripediaNetwork/issues/issues/940

### CODE REVIEW

**Review by Adebesin-Cell — APPROVED** [review]
Looks great 👍.

**Comment by Adebesin-Cell** [comment]
@Royal-lobster With the addition of the embed icon, I added a placeholder for now. the overflow still exists.

Screen Shot 2022-12-28 at 3 23 37 AM

**Review by Softdev1 — APPROVED** [review]
The current implementation looks pretty good now

**Comment by Royal-lobster** [comment]
> @Royal-lobster With the addition of the embed icon, I added a placeholder for now. the overflow still exists.
> 
> Screen Shot 2022-12-28 at 3 23 37 AM
> 

Oh good catch! i think we can again adjust the paddings in embeds plugin pr, i believe the placement of those icons are toggled internally by editor so we can make the adjustments after new icon is placed

**Comment by Adebesin-Cell** [comment]
> > @Royal-lobster With the addition of the embed icon, I added a placeholder for now. the overflow still exists.
> > Screen Shot 2022-12-28 at 3 23 37 AM
> 
> Oh good catch! i think we can again adjust the paddings in embeds plugin pr, i believe the placement of those icons are toggled internally by editor so we can make the adjustments after new icon is placed

Alright 👍👍

**Pull request merged**
