### PR TITLE
Adds open whitelist on dev

### PR DESCRIPTION
**Pull request by SidharthK2**
# Adds open whitelist on IQ testnet

- Deploy and integrate new whitelist contract with unrestricted whitelisting

## How should this be tested?

1. Whitelist your address here
https://testnet.braindao.org/address/0x9EF1c1Bf70d934F4200cA8a31359258c1c6be472?tab=write_contract

2. Try to edit/publish wiki on dev env

### Deployment

https://testnet.braindao.org/address/0x9EF1c1Bf70d934F4200cA8a31359258c1c6be472?tab=write_contract

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2975

### CODE REVIEW

**Review by Tolu-Mals — APPROVED** [review]

**Review by Damola18 — COMMENTED** [review]
https://github.com/user-attachments/assets/293eb639-bd0e-46a8-824b-7cf401f74e99



Publishing works as well as the "create-wiki"  button showing compared to the suggest wiki showing initially

**Comment by Tolu-Mals** [comment]
> Screen.Recording.2024-08-01.at.15.57.39.mov 
> Publishing works as well as the "create-wiki" button showing compared to the suggest wiki showing initially

"Create wiki" is the expected behaviour

**Comment by Damola18** [comment]
> > Screen.Recording.2024-08-01.at.15.57.39.mov 
> > Publishing works as well as the "create-wiki" button showing compared to the suggest wiki showing initially
> 
> "Create wiki" is the expected behaviour

**Comment by Damola18** [comment]
> > Screen.Recording.2024-08-01.at.15.57.39.mov 
> > Publishing works as well as the "create-wiki" button showing compared to the suggest wiki showing initially
> 
> "Create wiki" is the expected behaviour

Yeah, "suggest wiki" showed on the initial deployment I tested before this, that was why I clarified the changes

**Pull request closed without merging**
