### PR TITLE
UI Fix For Admin Panel

### PR DESCRIPTION
**Pull request by codiejay**
# PR title goes here
- [x]  Reduce width of date selector on graph. 
- [x] Arrow used in sort is different from the figma design
- [x] Status for wikis not archived is wrong.
- [x] The wiki table is not scaling well on larger screens
- [x] Tags on wiki table are overlapping on desktop screen
- [x] Typo on promote modal,
- [x] The primary buttons on the modals are wrong. 
- [x] This should be 'slot' and not sort 
- [x] The archive modal is not properly punctuated.
- [x] There is no status for editors' table. 
- [ ] The horizontal axis should be named in correlation
- [ ] Clicking on the question mark beside the promote button on promoted wikis should show a popup
- [ ] fix sort functionality, not accurate yet. 
- [ ] the pink colors are all wrong in dark mode
- [ ] The margin between the parge and the footer is too small

## Notes or observations

_jot down something here_

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/680

### CODE REVIEW

**Comment by kesar** [comment]
merging this pls open new pR w pending

**Comment by OleanjiKingCode** [comment]
> merging this pls open new pR w pending

@kesar  its like this pr was overwritten cos the main site isnt showing the same changes that i implented here

**Comment by kesar** [comment]
> > merging this pls open new pR w pending
> 
> @kesar its like this pr was overwritten cos the main site isnt showing the same changes that i implented here

can you point out what of the changes in https://github.com/EveripediaNetwork/ep-ui/pull/632/commits/fc22f87b9bf7ae16f25ba58d7b556675c284c6ac are not in main ?

**Comment by OleanjiKingCode** [comment]
> > > merging this pls open new pR w pending
> > 
> > 
> > @kesar its like this pr was overwritten cos the main site isnt showing the same changes that i implented here
> 
> can you point out what of the changes in [fc22f87](https://github.com/EveripediaNetwork/ep-ui/commit/fc22f87b9bf7ae16f25ba58d7b556675c284c6ac) are not in main ?

this is the commit i did 
image

this is how the main looks
image

**Comment by kesar** [comment]
it looks like a change from @codiejay https://github.com/EveripediaNetwork/ep-ui/commit/c0c882eae84d970a265ba7e6bae84b7f42f5c52c make sure you sync about this.

@OleanjiKingCode you can check blame in main and you will find this as well

Captura de Pantalla 2022-09-12 a las 22 08 57

or check what was the last commit who modified the page:

Captura de Pantalla 2022-09-12 a las 22 09 22

**Pull request merged**
