### PR TITLE
User profile page update

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# User profile page update

_Redesigns user profile page to fit the design

## How should this be tested?

1. Navigate to the user profile page
2. switch between wikis and edited tabs

link

Before
image

After
image

Fixes https://github.com/EveripediaNetwork/issues/issues/401

### CODE REVIEW

**Comment by Royal-lobster** [comment]
@Emmanueldmlr Great work, Looking awesome ! i found these tiny style issues

on mobile the username and share/settings needs some gap

CleanShot 2022-06-25 at 10 32 00@2x

there is some gap between profile banner and navbar 

CleanShot 2022-06-25 at 10 27 16@2x

i think the 'you have seen it all' message needs some padding at bottom, it is too near bottom of page

CleanShot 2022-06-25 at 10 28 23@2x

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
@Emmanueldmlr I am seeing that wikis I created and later edited are showing in my edits. Since I created them, I don't think they should be repeated in my edits.
Everything else looks good .

**Comment by Emmanueldmlr** [comment]
> @Emmanueldmlr I am seeing that wikis I created and later edited are showing in my edits. Since I created them, I don't think they should be repeated in my edits. Everything else looks good .

@Simplypheyie96, the issue is from the backend. @AshakaE  is the one responsible for it.

**Comment by kesar** [comment]
> > > @Emmanueldmlr I am seeing that wikis I created and later edited are showing in my edits. Since I created them, I don't think they should be repeated in my edits. Everything else looks good .
> > 
> > 
> > @Simplypheyie96, the issue is from the backend. @AshakaE is the one responsible for it.
> 
> I think it's fine if your created wiki shows in your edited section because you edited it 🌝

that would make tabs a nonsense. If you created 99 wikis and you edited 1, you go to the tab Edited to see which ones you were not created and you have to find it across 99 wikis.

prob. graph should allow different filters, (created, edited, all) and UI will show them depending on the needs for the UX

**Comment by AshakaE** [comment]
> > > > @Emmanueldmlr I am seeing that wikis I created and later edited are showing in my edits. Since I created them, I don't think they should be repeated in my edits. Everything else looks good .
> > > 
> > > 
> > > @Simplypheyie96, the issue is from the backend. @AshakaE is the one responsible for it.
> > 
> > 
> > I think it's fine if your created wiki shows in your edited section because you edited it 🌝
> 
> that would make tabs a nonsense. If you created 99 wikis and you edited 1, you go to the tab Edited to see which ones you were not created and you have to find it across 99 wikis.
> 
> prob. graph should allow different filters, (created, edited, all) and UI will show them depending on the needs for the UX

It should show the 1 edited out of the 99 created since it's edited, the rest will still be in created

**Comment by Simplypheyie96** [comment]
> > > > > @Emmanueldmlr I am seeing that wikis I created and later edited are showing in my edits. Since I created them, I don't think they should be repeated in my edits. Everything else looks good .
> > > > 
> > > > 
> > > > @Simplypheyie96, the issue is from the backend. @AshakaE is the one responsible for it.
> > > 
> > > 
> > > I think it's fine if your created wiki shows in your edited section because you edited it 🌝
> > 
> > 
> > that would make tabs a nonsense. If you created 99 wikis and you edited 1, you go to the tab Edited to see which ones you were not created and you have to find it across 99 wikis.
> > prob. graph should allow different filters, (created, edited, all) and UI will show them depending on the needs for the UX
> 
> It should show the 1 edited out of the 99 created since it's edited, the rest will still be in created

If you edit the 99, with the current format, the whole 99 will show in created & edited & that's not fine.
Take Instagram for example, your posts are in a different tabs, so are your reels. So wikis you created shouldn't be under your edits if you edited them yourself.

**Review by anubra266 — APPROVED** [review]

**Review by kesar — APPROVED** [review]

**Pull request merged**
