### PR TITLE
improving glossary ui page

### PR DESCRIPTION
**Pull request by Aliiiu**
# Improving Glossary UI Page

This PR works on improving the glossary page UI

## Notes or observations
image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2575

### CODE REVIEW

**Comment by Royal-lobster** [comment]
Very much better 🚀, also i think we can also reduce some more space and paddings

image


check this out - here i reduced padding around the alphabet line and made arrow background transparent so it won't cover up the content behind it

https://github.com/EveripediaNetwork/ep-ui/assets/52039218/de55c823-6c0f-4e37-b882-ca7619bc50ab

**Comment by Aliiiu** [comment]
> Very much better 🚀, also i think we can also reduce some more space and paddings
> 
> image
> check this out - here i reduced padding around the alphabet line and made arrow background transparent so it won't cover up the content behind it (in inspect element 😅)
> 
>  CleanShot.2024-04-29.at.11.04.50.mp4

image

On clicking the dropdown arrow it shows this. @Royal-lobster

**Comment by Royal-lobster** [comment]
> On clicking the dropdown arrow it shows this. @Royal-lobster

Oh yes, we can still show it when user clicks on the arrow, but before clicking, it can be with transparent background so user can get some more vertical space to explore the page

**Comment by Simplypheyie96** [comment]
> > On clicking the dropdown arrow it shows this. @Royal-lobster
> 
> Oh yes, we can still show it with background when user clicks on the arrow, but before clicking, it can be with transparent background so user can get some more vertical space to explore the page

great idea

**Comment by Aliiiu** [comment]
@Simplypheyie96 @Royal-lobster Please can you review again

**Comment by Royal-lobster** [comment]
Nice !!, We can still reduce the padding on alphabet line

CleanShot 2024-04-29 at 15 35 38@2x

**Comment by Simplypheyie96** [comment]
> Nice !!, We can still reduce the padding on alphabet line
> 
> CleanShot 2024-04-29 at 15 35 38@2x

we left the same comments at the same time. lool

**Comment by Aliiiu** [comment]
> > Nice !!, We can still reduce the padding on alphabet line
> > CleanShot 2024-04-29 at 15 35 38@2x
> 
> we left the same comments at the same time. lool

it is probably because the div is hidden. will reduce the padding and draw the div out

**Comment by Aliiiu** [comment]
@Royal-lobster @Simplypheyie96 Done with the new comment

**Review by Royal-lobster — APPROVED** [review]
Looks awesome 👏

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Royal-lobster** [comment]
Oh forgot mobile

**Comment by Aliiiu** [comment]
> Oh forgot mobile, We can remove this padding around the alphabet row:
> 
> CleanShot 2024-04-29 at 16 43 16@2x CleanShot 2024-04-29 at 16 47 51@2x
> 
> Also, @Simplypheyie96 Do you think it will be fine if we make the alphabet row scrollable on mobile ?

Reduced the padding for mobile

**Comment by Simplypheyie96** [comment]
> Oh forgot mobile, We can remove this padding around the alphabet row:
> 
> CleanShot 2024-04-29 at 16 43 16@2x CleanShot 2024-04-29 at 16 47 51@2x
> 
> Also, @Simplypheyie96 Do you think it will be fine if we make the alphabet row scrollable on mobile ?

instead of making it scrollable, we should just hide the alphabets in the arrows too on mobile.

**Comment by Royal-lobster** [comment]
> instead of making it scrollable, we should just hide the alphabets in the arrows too on mobile.
> image
> 

Makes sense as well

**Comment by Aliiiu** [comment]
@Simplypheyie96 @Royal-lobster Check now

**Comment by Simplypheyie96** [comment]
> @Simplypheyie96 @Royal-lobster Check now, let me know if there is anything I need to work on before I merge

it looks great. 👍🏿

**Pull request merged**
