### PR TITLE
Translate wiki content

### PR DESCRIPTION
**Pull request by Tolu-Mals**
# Summary
Adds a button to translate wikis when Korean is selected as the language

## Demo
https://github.com/EveripediaNetwork/ep-ui/assets/30352484/37ac63d8-cf3e-4bec-ae08-906adfeed2eb

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2165

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- dropdown is missing: 
image

- menu not translated in md/mobile breakpoint
image

**Comment by Tolu-Mals** [comment]
@Simplypheyie96 It's replaced with the Language section on mobile, so we could reuse components

Screenshot 2024-02-01 at 10 59 33 AM

**Comment by Simplypheyie96** [comment]
> @Simplypheyie96 Dropdown is replaced with the Language section on mobile, so we could reuse components. Will work on translations
> 
> Screenshot 2024-02-01 at 10 59 33 AM

this missing dropdown is on desktop.

**Comment by Tolu-Mals** [comment]
> * dropdown is missing:
> 
> image
> * menu not translated in md/mobile breakpoint
> 
> image

oh alright

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Softdev1** [comment]
SCR-20240201-naqg
Upon clicking the switch language toggle button I got this

**Comment by Tolu-Mals** [comment]
> SCR-20240201-naqg Upon clicking the switch language toggle button I got this

I'll work on that

**Comment by Tolu-Mals** [comment]
> SCR-20240201-naqg Upon clicking the switch language toggle button I got this

fixed

**Comment by kesar** [comment]
great work and thanks for adding the video. it looks awesome!

**Pull request merged**
