### PR TITLE
Implement media section

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Implement media section

_Implement media section

fixes https://github.com/EveripediaNetwork/issues/issues/305

### CODE REVIEW

**Comment by kesar** [comment]
i thought you were going to work in the same branch w @Royal-lobster to simplify changes that are required in both tasks

**Comment by Emmanueldmlr** [comment]
I thought we are working on two different features though. I will switch back to the branch he created.

**Comment by kesar** [comment]
can this PR be closed? if so pls do it

**Comment by Emmanueldmlr** [comment]
Yes, I already switched to the branch @Royal-lobster created.

**Pull request closed without merging**
