### PR TITLE
Activity fetch delay

### PR DESCRIPTION
**Pull request by SidharthK2**
# Activity fetch delay

Activity fetch had 3 sec delay

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2368

### CODE REVIEW

**Comment by kesar** [comment]
be careful because i think this 3 seconds delay its to avoid doing an infinite loading. I think the issue w activity page its at the API level, when I checked the chrome console the API took 10 seconds to respond

**Review by Softdev1 — APPROVED** [review]

**Comment by Softdev1** [comment]
@Adebesin-Cell  please review the code of this pr

**Comment by SidharthK2** [comment]
> @Adebesin-Cell please review the code of this pr

I am still working on it, probably a deeper issue.

**Comment by kesar** [comment]
this is backend related

**Pull request closed without merging**
