### PR TITLE
Feat add founders table

### PR DESCRIPTION
**Pull request by SidharthK2**
# Adds founders rank table

- Adds Founder table to Rank page
- Adds Founder table to homepage

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1927

### CODE REVIEW

**Review by Simplypheyie96 — COMMENTED** [review]
It looks okay without the wikis, well can only know if the table looks good once we see the stacked founders.

What to work on though is this extra space on mobile view after scrolling across the table @SidharthK2

**Comment by Simplypheyie96** [comment]
It looks okay with the stacked images. When it exceeds more than two founders we break it into an ellipse.

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
there is still so much space in the founder's tab which makes the rest of the table look squeezed together, let's reduce the space before the next tab, also the table are not aligned properly
Screenshot 2023-11-09 at 2 52 38 PM

Screenshot 2023-11-09 at 2 50 29 PM

**Comment by SidharthK2** [comment]
> there is still so much space in the founder's tab which makes the rest of the table look squeezed together, let's reduce the space before the next tab, also the table are not aligned properly Screenshot 2023-11-09 at 2 52 38 PM
> 
> Screenshot 2023-11-09 at 2 50 29 PM

image
Longer name rows might look messy if I reduce the gap too much.

**Review by Simplypheyie96 — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
