### PR TITLE
Modify activity page cards

### PR DESCRIPTION
**Pull request by Tolu-Mals**
Closes https://github.com/EveripediaNetwork/issues/issues/1249

In this pr, I implemented the new mobile layout for the cards on the activity page

Screenshots
<details>
<summary>Light mode</summary>
Screenshot 2023-05-05 at 1 35 13 PM
</details>

<details>
<summary>Dark mode</summary>
Screenshot 2023-05-05 at 1 35 22 PM
</details>

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
Let's change the category to defi because it'a too long on mobile


Also, the cards should have padding and content shouldn't get cut out. Maximum of 3lines for texts with truncation once it exceeds .

**Comment by Simplypheyie96** [comment]
@Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird

**Comment by Tolu-Mals** [comment]
> @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird

That makes sense.

> @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird

@Simplypheyie96 That was the only way to get the title and category to fit in one line in all possible situations without truncating the title too much. Let me know what you think about the latest version.

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Simplypheyie96** [comment]
> > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> 
> That makes sense.
> 
> > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> 
> @Simplypheyie96 That was the only way to get the title and category to fit in one line in all possible situations without truncating the title too much. Let me know what you think about the latest version.

I think its best to make the cards longer then if the title is too long such that the categories eould be displaced.

**Comment by Tolu-Mals** [comment]
> > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > 
> > 
> > That makes sense.
> > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > 
> > 
> > @Simplypheyie96 That was the only way to get the title and category to fit in one line in all possible situations without truncating the title too much. Let me know what you think about the latest version.
> 
> I think its best to make the cards longer then if the title is too long such that the categories eould be displaced.

By longer, are you referring to the width or height of the cards

**Comment by Simplypheyie96** [comment]
> > > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > > 
> > > 
> > > That makes sense.
> > > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > > 
> > > 
> > > @Simplypheyie96 That was the only way to get the title and category to fit in one line in all possible situations without truncating the title too much. Let me know what you think about the latest version.
> > 
> > I think its best to make the cards longer then if the title is too long such that the categories eould be displaced.
> 
> By longer, are you referring to the width or height of the cards

I mean height, 
But what crossed my mind now is that we can do abbreviations on mobile.

Organizations- org
People in crypto - pic
Decentralised finance - Defi
Exchanges- Exch/Ex
Nfts
Dapps
DAOs
Cryptocurrencies- crypto

**Comment by Tolu-Mals** [comment]
> > > > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > > > 
> > > > 
> > > > That makes sense.
> > > > > @Tolu-Mals other categories can remain the same since there is no short form. People standing alone instead of people in crypto feels weird
> > > > 
> > > > 
> > > > @Simplypheyie96 That was the only way to get the title and category to fit in one line in all possible situations without truncating the title too much. Let me know what you think about the latest version.
> > > 
> > > 
> > > I think its best to make the cards longer then if the title is too long such that the categories eould be displaced.
> > 
> > 
> > By longer, are you referring to the width or height of the cards
> 
> I mean height, But what crossed my mind now is that we can do abbreviations on mobile.
> 
> Organizations- org People in crypto - PIC Decentralised finance - Defi Exchanges- Exch/Ex Nfts Dapps DAOs Cryptocurrencies- crypto

Sounds good

**Review by Simplypheyie96 — APPROVED** [review]
Looks good

**Review by Royal-lobster — APPROVED** [review]
Code looks awesome !!

**Pull request merged**
