### PR TITLE
Fixes search char limit to 2

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
# Fixes search char limit to 2

This pull request updates the search functionality in our application by modifying the `CHAR_SEARCH_LIMIT` constant. Previously, the search would only initiate when a user had typed at least 3 characters. This limit has been reduced to 2 characters, allowing the search to begin sooner and potentially improving user experience by providing faster feedback when users are searching with shorter queries.

### Changes:
- Changed the `CHAR_SEARCH_LIMIT` from a hardcoded number to a constant for better clarity and maintainability.
- Reduced the `CHAR_SEARCH_LIMIT` from 3 to 2.

## How should this be tested?

1. **Initial Setup**: Ensure that the code changes are correctly implemented in your local or staging environment.
2. **Search Functionality Test**:
   - Navigate to [iq.wiki](https://iq.wiki) and use the navigation search bar.
   - Begin typing a search term. Notice that the search should now activate and begin fetching results as soon as you type 2 characters.
   - Test with a variety of inputs to ensure that the search triggers correctly at 2 characters and that results are relevant and accurate.
3. **Edge Case Handling**:
   - Test with single-character inputs to confirm that no search is triggered.
   - Test with special characters and numbers to assess how the search handles less typical input.

## Linked issues

Fixes: https://github.com/EveripediaNetwork/issues/issues/2745

### CODE REVIEW

**Comment by Tolu-Mals** [comment]
The search requests is starting at two characters, but it doesn't find anything, even when there's valid wikis

Screenshot 2024-06-06 at 10 35 15 AM
Screenshot 2024-06-06 at 10 35 23 AM

**Comment by Adebesin-Cell** [comment]
> The search requests is starting at two characters, but it doesn't find anything, even when there's valid wikis
> 
> Screenshot 2024-06-06 at 10 35 15 AM Screenshot 2024-06-06 at 10 35 23 AM

Screenshot 2024-06-06 at 11 14 43 AM
It's from backend.

cc: @AshakaE

**Comment by kesar** [comment]
please @Adebesin-Cell before asking for a code review test your code. This is obvious that it wasnt because backend has a limit of 3 chars.

https://github.com/EveripediaNetwork/ep-api/blob/main/src/App/Wiki/wiki.dto.ts#L28

**Comment by Adebesin-Cell** [comment]
> EveripediaNetwork/ep-api@`main`/src/App/Wiki/wiki.dto.ts#L28

Noted sir 👍, thx

**Comment by kesar** [comment]
image

api is up

**Comment by Adebesin-Cell** [comment]
Cool, thx

**Review by Tolu-Mals — APPROVED** [review]

**Comment by Softdev1** [comment]
Works fine for me .. well done @Adebesin-Cell 
Screenshot 2024-06-06 at 14 30 53

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
