### PR TITLE
Bot widget update

### PR DESCRIPTION
**Pull request by SidharthK2**
# Improve design and add posthog to bot widget

- Remove next buttons and make chat scrollable
- Add posthog to capture widget open event, suggestion prompts.

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2943

### CODE REVIEW

**Review by Simplypheyie96 — COMMENTED** [review]
Great Job.
Let's center this content and we can close the issue
image

**Comment by SidharthK2** [comment]
> Great Job. Let's center this content and we can close the issue image

Do you mean the suggestions?

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Softdev1** [comment]
@SidharthK2  let's get a co-engineer to review the code-base part of this issue , so we don't keep this issue too long

**Review by Damola18 — COMMENTED** [review]
Code looks good!

Few changes

image

1. The UI of the first design doesn't seem to be on the implementation. Any reason why that is?

2. The text on the UI has been updated from "Hi There! Here are some cool stuff i can do for you" to "Hi There! I am the IQ GPT Chatbot. Here are some cool stuff i can do for you." You can update that as well.

3. The placeholder text for the input field should be updated as well.


4. Screenshot 2024-08-07 at 11 06 50
Let's have the font size of the bot responses reduced from '14px' to '12px' as specified on the UI. It looks bigger

**Review by Damola18 — APPROVED** [review]

**Review by Damola18 — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
