### PR TITLE
Fixes Trending Wikis Carousel Dots

### PR DESCRIPTION
**Pull request by Royal-lobster**
Fixes https://github.com/EveripediaNetwork/issues/issues/436

# Changes
- reimplemented notable drops carousel with existing slider component

# Links
- https://monopedia-ui-git-trending-wiki-dots-prediqt.vercel.app/

# Screenshots

### With Multiple cards

https://user-images.githubusercontent.com/52039218/174763229-4c3a294d-b1e4-403d-9e77-3196ec2b9c50.mp4

### Responsive test

https://user-images.githubusercontent.com/52039218/174763342-bbf918bb-9f7c-49fd-b137-0f86442fdd80.mp4

### CODE REVIEW

**Review by anubra266 — APPROVED** [review]

**Review by Simplypheyie96 — APPROVED** [review]
well done @Royal-lobster it looks great

**Comment by Royal-lobster** [comment]
> @Royal-lobster one thing you can do is make the indicators visible in dark mode 

Thanks for pointing out ! i will make the change

**Comment by Royal-lobster** [comment]
@Simplypheyie96 implemented the changes.

**Review by kesar — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
image
@Simplypheyie96, it looks more like the dots are not so visible.

**Comment by Simplypheyie96** [comment]
> image
> 
> @Simplypheyie96, it looks more like the dots are not so visible.

It's fine. It's overly important to point attention there

**Pull request merged**
