### PR TITLE
update content from docs

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
update content from docs

fixes https://github.com/EveripediaNetwork/issues/issues/1076

### CODE REVIEW

**Comment by Softdev1** [comment]
Please update the following : under Braindao page 
SCR-20230228-g9j
@Adebesin-Cell

**Comment by Softdev1** [comment]
Then here 
SCR-20230228-gbt

**Comment by Simplypheyie96** [comment]
> Please update the following : under Braindao page SCR-20230228-g9j @Adebesin-Cell

why tho?
it's not just any calculator but a reward calculator

**Comment by Softdev1** [comment]
@kesar  requested the changes via a docs @Simplypheyie96

**Comment by Softdev1** [comment]
https://docs.google.com/document/d/1AnNRwWLEbBa2jWMvGWPtWQhoS43w5Hsi6CSilVzgmT8/edit#heading=h.pesopfeg8nd4 here is the docs @Simplypheyie96

**Comment by Softdev1** [comment]
SCR-20230228-ge0
Please update this too

**Review by Softdev1 — APPROVED** [review]
Please i have dropped some feedback from

**Pull request merged**
