### PR TITLE
Bundle size improvements

### PR DESCRIPTION
**Pull request by Royal-lobster**
Closes https://github.com/EveripediaNetwork/issues/issues/698
# Changes
- removed sentry 
- made wagmi load dynamic
- made layout and navbar elements containing crypto libraries to lazy load
- makes hero image set to priority loading for LCP

### CODE REVIEW

**Comment by kesar** [comment]
it looks good from my testing, going to yolo deploy and see if someone complains / we get better numbers on vercel

**Comment by kesar** [comment]
weirdly it still takes all the magic assets on checking https://web.dev/measure/?url=https%3A%2F%2Fiq.wiki

**Comment by Royal-lobster** [comment]
> weirdly it still takes all the magic assets on checking https://web.dev/measure/?url=https%3A%2F%2Fiq.wiki

i think it's probably calculating after page load

**Comment by kesar** [comment]
but a web crawler shouldnt get the wagmi unless they use it

**Comment by Royal-lobster** [comment]
> but a web crawler shouldnt get the wagmi unless they use it 

Ohh, currently we are lazy loading all times in _app.ts for initiating wagmi client, i will test out if we can lazy load it on demand.

**Pull request merged**
