### PR TITLE
Shorten Create Wiki

### PR DESCRIPTION
**Pull request by anubra266**
Resolves EveripediaNetwork/issues#284

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
image
@anubra266 ,I got this when I tried to visit the create-wiki page.

**Comment by Emmanueldmlr** [comment]
image
I think the error.

**Comment by anubra266** [comment]
> image
> 
> I think the error.

Oh...I know what caused that. Thanks

**Comment by anubra266** [comment]
@kesar I just tried to separate the page local state.

**Review by kesar — APPROVED** [review]

**Pull request merged**
