### PR TITLE
Event page

### PR DESCRIPTION
**Pull request by Aliiiu**
# Event Page UI Implementation

This PR works on the implementation of the event page 

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/2083

### CODE REVIEW

**Comment by Aliiiu** [comment]
@Simplypheyie96  @Softdev1  I am done with the implementation. You can test now

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
On the trending section, for the initial ellipse, there shouldn't be any cards showing on the side like this. the back arrow should only show after the user has used the forward scroll.
Screenshot 2024-02-15 at 11 33 37 AM

---
The search result shouldn't have the trending and tags so search results can easily be seen.
image

---
this should be underlined on hover to indicate that it's a link. The back arrow button is missing too
image

---
Let's make the whole card clickable
image

---
these should show they are clickable on hover just like the register button (using the hover point)
image

---
suggest event button not working yet on the empty state. it should show the dialogue box on click.
image

---
on figma, there are 2 designs for md breakpoint for bigger md and smaller md, this bp is not working for this md (viewport: 820 x 1180)
image

**Comment by Aliiiu** [comment]
> On the trending section, for the initial ellipse, there shouldn't be any cards showing on the side like this. the back arrow should only show after the user has used the forward scroll. Screenshot 2024-02-15 at 11 33 37 AM
> 
> The search result shouldn't have the trending and tags so search results can easily be seen. image
> 
> this should be underlined on hover to indicate that it's a link. The back arrow button is missing too image
> 
> Let's make the whole card clickable image
> 
> these should show they are clickable on hover just like the register button (using the hover point) image
> 
> suggest event button not working yet on the empty state. it should show the dialogue box on click. image
> 
> on figma, there are 2 designs for md breakpoint for bigger md and smaller md, this bp is not working for this md (viewport: 820 x 1180) image

Then we won't have the autoplay feature. The UX for that behaviour is if we have a finite number of slides but with the autoplay feature we theoretically make the slides infinite. So we can't monitor a starting position or end.

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Adebesin-Cell** [comment]
Kindly fix the conflicts

**Comment by Tolu-Mals** [comment]
This is different from the design

Screenshot 2024-02-15 at 3 56 18 PM

**Comment by Tolu-Mals** [comment]
Screenshot 2024-02-15 at 4 02 53 PM

Calendar icon should be grayed out like the search icon on dark mode

**Comment by Tolu-Mals** [comment]
Icon in the left slider button isn't positioned properly

Screenshot 2024-02-15 at 4 04 07 PM

**Comment by Tolu-Mals** [comment]
This navbar for the md breakpoint isn't implemented

Screenshot 2024-02-15 at 4 08 28 PM

**Comment by Tolu-Mals** [comment]
Some spacing is needed in between the lines
Screenshot 2024-02-15 at 4 11 21 PM

**Comment by Tolu-Mals** [comment]
Other than those, everything looks great ✨

**Review by Tolu-Mals — APPROVED** [review]

**Comment by Aliiiu** [comment]
> This navbar for the md breakpoint isn't implemented
> 
> Screenshot 2024-02-15 at 4 08 28 PM

It's a different task. Someone else is working on it

**Comment by Aliiiu** [comment]
> @Softdev1 we'd need an issue for Korean translations on this page

**Review by Softdev1 — APPROVED** [review]

**Pull request merged**
