### PR TITLE
Fix superwalk converter

### PR DESCRIPTION
**Pull request by Aliiiu**
# Fix SuperWalk Converter

This PR works on resolving issue with the converter on the superwalk wiki and the broken image for the wiki

## How should this be tested?

1. Search the superwalk and navigate to the wiki
2. Scroll down to the converter section and test it out

## Notes or observations

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2851

### CODE REVIEW

**Review by Softdev1 — APPROVED** [review]

**Review by Adebesin-Cell — COMMENTED** [review]
This PR contains unrelated fixes from https://github.com/EveripediaNetwork/ep-ui/pull/1916/, making it difficult to review code changes, kindly fix the mixed files perhaps by setting upstream branch to pwa-fixes.

Click in edit to change base branch
Screenshot 2024-07-03 at 5 42 35 PM

**Comment by kesar** [comment]
how this solve the issue?¿

**Comment by Aliiiu** [comment]
> how this solve the issue?¿

The issue was because of the slug from the Coingecko link used to get the tokenStats. On investigating I realised the slug won't return the right data for the token so I used an alternative slug that works.

image

The issue was resolved by updating the Coingecko link of the wiki to pass the right slug.

image

I will close the PR without merging. None of the files changed solves the issue.

**Comment by kesar** [comment]
but how is this PR affecting that? what line actually solves it ?

**Comment by Aliiiu** [comment]
> but how is this PR affecting that? what line actually solves it ?

 None of the files changed solves the issue. I mistakenly checked out from the PWA task branch I was working on.

**Comment by Aliiiu** [comment]
> but how is this PR affecting that? what line actually solves it ?

The issue has been resolved but it did not need a PR, all it needs was just updating the coingecko link

**Comment by Aliiiu** [comment]
@Adebesin-Cell Cleaned the PR

**Comment by kesar** [comment]
ahh okok. when this happens just feel free to comment in the original issue and close it with the explanation :) no need to open a dummy PR 👍🏻 👍🏻

**Comment by Aliiiu** [comment]
> ahh okok. when this happens just feel free to comment in the original issue and close it with the explanation :) no need to open a dummy PR 👍🏻 👍🏻

Noted, thank you sir

**Pull request closed without merging**
