### PR TITLE
Wiki crashing

### PR DESCRIPTION
**Pull request by Aliiiu**
# Wiki Crashing

This PR works on resolving caching issue when using the app with next-pwa.

Fixes https://github.com/EveripediaNetwork/issues/issues/3030

### CODE REVIEW

**Comment by Adebesin-Cell** [comment]
Is this still in progress?

**Comment by Adebesin-Cell** [comment]
Perhaps we give this a try on prod? @Tolu-Mals 

Though from testing I can't seem to replicate any cache with translation.

**Comment by Adebesin-Cell** [comment]
YOLO 🚀

**Comment by Tolu-Mals** [comment]
> Perhaps we give this a try on prod? @Tolu-Mals
> 
> Though from testing I can't seem to replicate any cache with translation.

yeah seems to work fine

**Pull request merged**
