### PR TITLE
Support youtube videos on uploads

### PR DESCRIPTION
**Pull request by codiejay**
https://user-images.githubusercontent.com/30846348/177564862-98ef03fa-2e3b-45e0-a713-fe90a29bceba.mov

## Linked issues

closes #462, closes #462, closes https://github.com/EveripediaNetwork/issues/issues/462

@Softdev1 test with [this link](https://monopedia-ui-git-462-support-youtube-videos-on-uploads-prediqt.vercel.app/), please.

### CODE REVIEW

**Comment by kesar** [comment]
can u pls add a video of how it works to the issue? thanks!

**Comment by codiejay** [comment]
> can u pls add a video of how it works to the issue? thanks!

sure!

**Comment by kesar** [comment]
we need to change some texts that @Softdev1 will sync w you about the paste link text and image drop

**Comment by Softdev1** [comment]
@codiejay  kindly consider the above description and syn up with me, if you need more understanding on what to do.

**Review by kesar — APPROVED** [review]

**Pull request merged**
