### PR TITLE
Feat/homepage iq

### PR DESCRIPTION
**Pull request by SidharthK2**
# homepage IQ integration

image

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/2292

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- please adjust spacing between the sections, it is currently too large. The distance between the headline and the new infographic card should be the same with the cards below the infographics to have a visually balanced look.
image

---
- selection on the historical graph needs to work like the graph on iq dashbaord. and also the price metric on the graph is missing.
image

--
DESIGN (updated design to demonstrate)
image

---
- Binance logo should be white in dark mode.
image

- similar issues in the breakpoints too.
- The arrangement of sections doesn't look similar to design in tablet view.
- the headline is covered in mobile breakpoint.
image

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- everything looks good in mobile view.
- the arrangement on tablet view is still kinda weird.
image
--
it should look more like this 
image

--
- let's close up this gap more.
image

---
something like this:
image

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by kesar** [comment]
Lets add in the same PR the adding Wiki powered by IQ on the wikis as well 👍🏻 

few changes:

Captura de pantalla 2024-03-22 a las 14 23 09

text is cut on my desktop
iq pricing graph looks very flat default to 1M and explain that somewhere in the graph

the "high today" it looks super weird. Not sure where that copy comes from. the -7% (background green) high today its hard to understand. Bg green usually its positive.

We dont want to emphasize the difference of gaining / loosing w a big bg because that can be in red sometimes. 

If you check as example our dashboard or coingecko or cmc those numbers are usually smaller

Captura de pantalla 2024-03-22 a las 14 28 49
Captura de pantalla 2024-03-22 a las 14 28 46
Captura de pantalla 2024-03-22 a las 14 28 41
Captura de pantalla 2024-03-22 a las 14 29 30

**Comment by Simplypheyie96** [comment]
@kesar 
image

**Comment by kesar** [comment]
> @kesar Seeing the black and white icons of the exchanges, i think the real icon logos look bettter image

sure we can give it a try, besides that, changes looks great! thanks! 

lets ensure wiki page also gets updated plz. Thanks!

**Comment by Softdev1** [comment]
image
Please let's fix this and also implement other feedback

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- These metrics shouldn't have any backgrounds 
image

---
- this should have "in 1month" in front of it in brackets like the design
image

---
- there is an issue with spacing on md/sm breakpoints
image
image


# on the design
image
image

**Review by Simplypheyie96 — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]
Nice now ... 👍 well-done @Simplypheyie96  @SidharthK2

**Pull request merged**
