### PR TITLE
Wiki views tracker

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Wiki Views Tracker and Admin UI update

Before :

image

image

Now:

image

image

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1185

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
according to the prompt on the issue page, the graph has to be in dates, so it can correlate with the table. implement according to the design.
image

**Comment by OleanjiKingCode** [comment]
Yes that's dummy data for now until the data is gotten form the backend

**Comment by Simplypheyie96** [comment]
> Yes that's dummy data for now until the data is gotten form the backend

i am talking about the days below, mon, tues,wed,
In the design, you'll see it as day/month (dates). not just name of days
image

**Comment by kesar** [comment]
for simplicity API just returns days, so no need the dropdown. also just make the chart to be last 365 days (or less if we have less data, i think rn we might have only 6 months back)

**Comment by Simplypheyie96** [comment]
> for simplicity API just returns days, so no need the dropdown. also just make the chart to be last 365 days (or less if we have less data, i think rn we might have only 6 months back)

@OleanjiKingCode that means the graph will be this way without the daily dropdown we had going before
image

**Comment by OleanjiKingCode** [comment]
image

image

image

**Comment by OleanjiKingCode** [comment]
@kesar now thats there visits count, how does the user data with editors and visitors work

**Review by Adebesin-Cell — COMMENTED** [review]
Screen Shot 2023-04-20 at 2 26 39 PM

Weirdly, no data is showing for editors. :))

**Comment by OleanjiKingCode** [comment]
Yeah, true but that's not part of my pr

**Comment by Adebesin-Cell** [comment]
> Yeah, true but that's not part of my pr

Data shows on search tho 🙂. Look into it and see what's the cause, maybe if it's something huge you can make a new PR.
I think it's from this PR @AshakaE, look at the backend maybe.

## Main branch currently.
Screen Shot 2023-04-20 at 2 38 56 PM

**Review by Royal-lobster — APPROVED** [review]

**Pull request merged**
