### PR TITLE
Upgrade Wagmi Version

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Upgrade Wagmi Version

_As a developer, I would want to test the beta version of WAGMI ("wagmi": "1.0.0-next.0") on IQ.wiki

fixes https://github.com/EveripediaNetwork/issues/issues/1271

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@kesar,  We will need a wallet connect project Id. It's now a parameter for the connector in place of the QR code. https://cloud.walletconnect.com/sign-in

**Comment by kesar** [comment]
> @kesar, We will need a wallet connect project Id. It's now a parameter for the connector in place of the QR code. https://cloud.walletconnect.com/sign-in

2ced0521cd6b12cfeed59ad96545215f

**Comment by Emmanueldmlr** [comment]
@Softdev1 , this PR is ready.

**Comment by Emmanueldmlr** [comment]
@Softdev1 , Please, hold on with it

**Review by Royal-lobster — APPROVED** [review]

**Pull request merged**
