### PR TITLE
Rtk response types and queries refactor

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
Rtk refactor fix

closes https://github.com/EveripediaNetwork/issues/issues/993

### CODE REVIEW

**Comment by kesar** [comment]
this has been 2 weeks open, please lets merge or close

**Comment by Adebesin-Cell** [comment]
> this has been 2 weeks open, please lets merge or close

Yeah! Still working on it. I’ll make it ready for review tomorrow 🙏.

**Comment by Adebesin-Cell** [comment]
Weird, why is codeclimate checking?? @Royal-lobster

**Comment by Royal-lobster** [comment]
> Weird, why is codeclimate checking?? @Royal-lobster

Probably its because this is ongoing pr since the integration. i think it should not check for new PRs

**Comment by Royal-lobster** [comment]
CleanShot 2023-02-21 at 22 00 36@2x

This is good start ! also there are still few left. the goal is to make all Wiki / Activity types to scoped down to what we are using in query.

**Review by Royal-lobster — APPROVED** [review]

**Comment by Adebesin-Cell** [comment]
I think we can work other rtk queries later.

**Comment by Royal-lobster** [comment]
> I think we can work other rtk queries later.

Yep ! i think this looks good for merge.

**Pull request merged**
