### PR TITLE
Fix theme glitch

### PR DESCRIPTION
**Pull request by Tolu-Mals**
# Summary
Closes https://github.com/EveripediaNetwork/issues/issues/1549. 

I think this pr should finally fix this bug. The approach is to use a script that blocks the UI while determining the correct theme and then set's the `data-theme` property on the html element (which sets the app's theme). There's the flash of a blank white page before the UI shows, but I don't think that's an issue.

### CODE REVIEW

**Comment by Tolu-Mals** [comment]
still has some issues lol, working on it

**Comment by Tolu-Mals** [comment]
Everything should work fine now

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Tolu-Mals** [comment]
still didn't work 😬

**Comment by Tolu-Mals** [comment]
I think the script isn't running on production, I'm not sure why

**Pull request merged**
