### PR TITLE
Review Event Page

### PR DESCRIPTION
**Pull request by Aliiiu**
# Review Event Page

This PR works on 
- Hiding the Nearby event feature on the page from the public while we begin to fix the issue and test it properly.
- Sorting the events on the homepage by most recent for instance the recent event should be in August 2024 by properly sorting
- Archiving Old events

## How to test
- Go to events page, check if the events are starting from the current date upward
- Try testing out all filters to see if all they start from the current date upwards
- Confirm if nearbyEvent widget is hidden on events and events/:id
- Open any wiki, create a new event metadata, update and also remove. Confirm if it works fine
- do the same for an event wiki

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/3016

### CODE REVIEW

**Review by Simplypheyie96 — APPROVED** [review]

**Comment by Tolu-Mals** [comment]
Search doesn't work fine. Also pressing enter on the search input reloads the page.

Screenshot 2024-08-27 at 2 36 59 PM

**Comment by Aliiiu** [comment]
> Search doesn't work fine. Also pressing enter on the search input reloads the page.
> 
> Screenshot 2024-08-27 at 2 36 59 PM

Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon

**Comment by Tolu-Mals** [comment]
> > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > Screenshot 2024-08-27 at 2 36 59 PM
> 
> Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon

We do, 100% sure

**Comment by Aliiiu** [comment]
> > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > Screenshot 2024-08-27 at 2 36 59 PM
> > 
> > 
> > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> 
> We do, 100% sure

Can't find it in the current list

**Comment by Tolu-Mals** [comment]
> > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > Screenshot 2024-08-27 at 2 36 59 PM
> 
> Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon

I didn't mention any issue with clicking the icon. I 

> > > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > > Screenshot 2024-08-27 at 2 36 59 PM
> > > 
> > > 
> > > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> > 
> > 
> > We do, 100% sure
> 
> Can't find it in the current list

It got removed after my comment

**Comment by Aliiiu** [comment]
> > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > Screenshot 2024-08-27 at 2 36 59 PM
> > 
> > 
> > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> 
> I didn't mention any issue with clicking the icon. I
> 
> > > > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > > > Screenshot 2024-08-27 at 2 36 59 PM
> > > > 
> > > > 
> > > > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> > > 
> > > 
> > > We do, 100% sure
> > 
> > 
> > Can't find it in the current list
> 
> It got removed after my comment

Haaa

**Comment by Tolu-Mals** [comment]
Try searching 

> > > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > > Screenshot 2024-08-27 at 2 36 59 PM
> > > 
> > > 
> > > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> > 
> > 
> > I didn't mention any issue with clicking the icon. I
> > > > > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > > > > Screenshot 2024-08-27 at 2 36 59 PM
> > > > > 
> > > > > 
> > > > > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> > > > 
> > > > 
> > > > We do, 100% sure
> > > 
> > > 
> > > Can't find it in the current list
> > 
> > 
> > It got removed after my comment
> 
> Haaa

maybe Ashaka is working on the api or something

**Comment by Aliiiu** [comment]
Alright will resolve the issue with pressing enter that reloads the page

**Comment by Tolu-Mals** [comment]
> > > > Search doesn't work fine. Also pressing enter on the search input reloads the page.
> > > > Screenshot 2024-08-27 at 2 36 59 PM
> > > 
> > > 
> > > Will resolve that issue of clicking the icon. I don't think we have a current event with the name Lexicon
> > 
> > 
> > We do, 100% sure
> 
> Can't find it in the current list

https://iq-wiki-i4i4x850e-prediqt.vercel.app/wiki/lexicon-2024/

**Comment by Tolu-Mals** [comment]
> > https://iq-wiki-i4i4x850e-prediqt.vercel.app/wiki/lexicon-2024/
> 
> Yes, you can still see past events. But we are showing current events only with startDate of "2024-08-27"

https://app.usebubbles.com/vTuohA45cY1sJFDqqoPHSU

**Comment by Aliiiu** [comment]
> https://app.usebubbles.com/vTuohA45cY1sJFDqqoPHSU

Interesting, it might be a cached data.

**Comment by Tolu-Mals** [comment]
when I enter a date range in the search bar, it doesn't return the results in any order, I think it should be in ascending order as well. for example, 1st to 31st of october currently returns events in this order: 31st, 26th, 5th, 7th.

**Comment by Tolu-Mals** [comment]
Results are not consistent when I apply multiple filters

When I applied a fliter for Africa I get this
Screenshot 2024-08-28 at 10 55 14 AM

But when I add 'Next Week' and 'Conference' along with 'Africa', I'm getting a conference that happens in UAE, which didn't show when I filtered only by 'Africa'

Screenshot 2024-08-28 at 10 54 55 AM

**Comment by Aliiiu** [comment]
> Results are not consistent when I apply multiple filters
> 
> When I applied a fliter for Africa I get this Screenshot 2024-08-28 at 10 55 14 AM
> 
> But when I add 'Next Week' and 'Conference' along with 'Africa', I'm getting a conference that happens in UAE, which is in Asia.
> 
> Screenshot 2024-08-28 at 10 54 55 AM

Nice catch, will look into it

**Comment by Tolu-Mals** [comment]
I noticed that when I update an event, add or delete an event in a wiki, it doesn't always reflect in the history of the wiki. or maybe it takes a while, I"m not sure .

**Comment by Aliiiu** [comment]
> I noticed that when I update an event, add or delete an event in a wiki, it doesn't always reflect in the history of the wiki. or maybe it takes a while, I"m not sure .

I don't think I get this, how do you check history of a wiki. If you mean the wiki showing on activity page, that might be a caching issue and we don't revalidate cache on preview links. so you have to refresh the page.

**Comment by Aliiiu** [comment]
> when I enter a date range in the search bar, it doesn't return the results in any order, I think it should be in ascending order as well. for example, 1st to 31st of october currently returns events in this order: 31st, 26th, 5th, 7th.

This has been resolved.

**Comment by Tolu-Mals** [comment]
> > I noticed that when I update an event, add or delete an event in a wiki, it doesn't always reflect in the history of the wiki. or maybe it takes a while, I"m not sure .
> 
> I don't think I get this, how do you check history of a wiki?. If you mean the wiki showing on activity page, that might be a caching issue and we don't revalidate cache on preview links. so you have to refresh the page.

yeah it shows now, it just took a while to reflect

**Review by Tolu-Mals — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]
Looks great :)

**Review by AshakaE — APPROVED** [review]

**Pull request merged**
