### PR TITLE
Homepage improvement

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Homepage Improvement

Before
image

After
image

fixes https://github.com/EveripediaNetwork/issues/issues/316

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
on xl. I will fix it now.

**Comment by Emmanueldmlr** [comment]
@kesar, can you confirm it works fine now?.

**Comment by kesar** [comment]
still off

image

image

**Comment by Emmanueldmlr** [comment]
What's your screen resolution?.

**Comment by kesar** [comment]
can we make the bg in white a bit more visible ? plz

**Review by kesar — APPROVED** [review]

**Pull request merged**
