### PR TITLE
Media upload improvement

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Media upload improvement

_Redesign the media upload modal following the new design on the Figma page.

## How should this be tested?

1. go to the create wiki page
2. click on the new image or video button
3. You should have two options (Drag and drop & upload a link)  through which you can upload your media

Before
image

After
image

fixes https://github.com/EveripediaNetwork/issues/issues/390

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
image

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
Looks great. Just this tiny thing. Is it possible that we can have the image link disappear once the picture is uploaded, because they might be confused with the error message that shows up when trying to clear the link to post another. 
image

**Comment by JustinCast** [comment]
> image After several images were uploaded the dialog layout got cut

Maybe we can set a max media limit

**Comment by Emmanueldmlr** [comment]
> > image After several images were uploaded the dialog layout got cut
> 
> Maybe we can set a max media limit

@Simplypheyie96 and @kesar  , what should we do about this?

**Comment by Emmanueldmlr** [comment]
> Looks great. Just this tiny thing. Is it possible that we can have the image link disappear once the picture is uploaded, because they might be confused with the error message that shows up when trying to clear the link to post another. image

no problem. I will fix it

**Comment by Simplypheyie96** [comment]
> > > image After several images were uploaded the dialog layout got cut
> > 
> > 
> > Maybe we can set a max media limit
> 
> @Simplypheyie96 and @kesar , what should we do about this?

first off, we need to reduce the size of this box, then add beside the 10mb max size, we write something like (10mb max/10media files). but the first thing that comes to mind is to have a scroll bar on there
image

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, I'm not sure if a scroll bar is a better UI. I think we should reduce the max no of uploads instead.

**Comment by Simplypheyie96** [comment]
image
something like this @Emmanueldmlr

**Comment by Emmanueldmlr** [comment]
@Simplypheyie96, can you update the properties on Figma, so I can work with the new properties.

**Comment by Simplypheyie96** [comment]
> @Simplypheyie96, can you update the properties on Figma, so I can work with the new properties.

it is on figma

**Comment by kesar** [comment]
image

👍🏻

**Comment by Royal-lobster** [comment]
@Emmanueldmlr This is working awesome ! 

And i noticed that the file names can be a bit longer as it is truncating half way 

CleanShot 2022-06-08 at 14 14 19@2x

@Simplypheyie96, i think the heading local files no longer represent this since the files are uploaded to ipfs immediately but i am not sure if it may mislead some users

**Comment by Emmanueldmlr** [comment]
> @Emmanueldmlr This is working awesome !
> 
> And i noticed that the file names can be a bit longer as it is truncating half way
> 
> CleanShot 2022-06-08 at 14 14 19@2x
> 
> @Simplypheyie96, i think the heading local files no longer represent this since the files are uploaded to ipfs immediately but i am not sure if it may mislead some users

I will fix it now
@Simplypheyie96, I'm still waiting for your review.

**Comment by Simplypheyie96** [comment]
> > @Emmanueldmlr This is working awesome !
> > And i noticed that the file names can be a bit longer as it is truncating half way
> > CleanShot 2022-06-08 at 14 14 19@2x
> > @Simplypheyie96, i think the heading local files no longer represent this since the files are uploaded to ipfs immediately but i am not sure if it may mislead some users
> 
> I will fix it now @Simplypheyie96, I'm still waiting for your review.

It looks great. 
For the local files that @Royal-lobster suggested, it can be changed to Uploads @Emmanueldmlr 
image

**Comment by Emmanueldmlr** [comment]
Just to confirm, change Local files to Upload files?... @Simplypheyie96

**Comment by Simplypheyie96** [comment]
> Just to confirm, change Local files to Upload files?... @Simplypheyie96

no, to just "Uploads"... indicating to the users that files they upload will be displayed in the box below.
image

**Comment by Emmanueldmlr** [comment]
image

@Simplypheyie96 @Royal-lobster , fixed all issues now.

**Review by kesar — APPROVED** [review]

**Review by Royal-lobster — APPROVED** [review]

**Pull request merged**
