### PR TITLE
Made state in create-wiki to change when slug changes

### PR DESCRIPTION
**Pull request by Royal-lobster**
Fixes https://github.com/EveripediaNetwork/issues/issues/237
Fixes https://github.com/EveripediaNetwork/issues/issues/232

# Testing the changes
**[Test link with buttons]** - This branch is for testing purpose for buttons and will be deleted after this PR closes
https://monopedia-ui-git-test-fix-create-wiki-state-prediqt.vercel.app/create-wiki?slug=summary-test-wiki

**[Live Link]** - 
https://monopedia-ui-git-fix-edit-to-create-wiki-empty-prediqt.vercel.app/create-wiki?slug=summary-test-wiki

# Changes 
1. Made the state of editor to change when slug changes
2. Re-fixed editor focus problem when content changes with editor instance
3. Created a reset action in wiki-slice to reset the state when there is no slug (new create-wiki page)
4. Made the image to reset when there is no slug
5. Updated use-effect dependencies in create-wiki as per eslint suggestions
6. Fixed editor to populate initial page template correctly (Now page template overrides the editor only when editor is empty or it is populated with other page template)

### CODE REVIEW

**Review by kesar — APPROVED** [review]

**Comment by JustinCast** [comment]
image
When I try to change the summary and submit it again, I got this

**Comment by Royal-lobster** [comment]
@JustinCast Ohh thanks ! I tried to change and submit but it worked fine for me

image

Can you try to edit again ?

**Comment by JustinCast** [comment]
image
It seems there are several relayer requests being made. That's causing an overload of the service. Wondering if it's related with any change introduced in this PR or if it's already in the main branch

**Comment by JustinCast** [comment]
> image
> 
> It seems there are several relayer requests being made. That's causing an overload of the service. Wondering if it's related with any change introduced in this PR or if it's already in the main branch

image

**Comment by Royal-lobster** [comment]
> It seems there are several relayer requests being made. That's causing an overload of the service. Wondering if it's related with any change introduced in this PR or if it's already in the main branch

Opps Thanks ! I am sure its from this PR since i changed the useEffect dependencies. I will check out what is triggering it.

**Comment by Royal-lobster** [comment]
image

Now its resolved

**Comment by kesar** [comment]
> > image
> > It seems there are several relayer requests being made. That's causing an overload of the service. Wondering if it's related with any change introduced in this PR or if it's already in the main branch
> 
> image

great catch!

**Review by JustinCast — COMMENTED** [review]
@kesar @Royal-lobster it's weird that after I change the wiki summary of a wiki and reload the editor with the last slug it presents no information at all

**Comment by Royal-lobster** [comment]
> @kesar @Royal-lobster it's weird that after I change the wiki summary of a wiki and reload the editor with the last slug it presents no information at all. It's happening for you also?

Ohh i just checked it and it seems to be fine. which slug did you edit ?

**Comment by kesar** [comment]
I would say lets get this merged once conflict is fixed and if we are able to reproduce the issue, we open a bug issue related since this is solving other current bugs 👍🏻

**Pull request merged**
