### PR TITLE
Fix Theme Glitch

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
## Fix Theme Glitch

Closes https://github.com/EveripediaNetwork/issues/issues/1462

### Bug

When the page is initially loaded, an issue occurs where the client color mode experiences a glitch in dark mode. The glitch manifests as white and dark lines appearing on the screen before the proper background is set.

### Changes
- Added "dark" as the ``initialColorMode`` property in the ``theme.tsx``.
- Updated the ``_document.tsx`` file to address the glitch in the dark mode transition.

### Media 

https://github.com/EveripediaNetwork/ep-ui/assets/66301634/0ef794d2-aff4-45fc-8052-523b4f00ac78

### CODE REVIEW

**Review by Tolu-Mals — APPROVED** [review]

**Comment by Royal-lobster** [comment]
Haha works as magic 😅 but its showing dark theme for light mode users by default unless they change it back to light mode manually (system theme adaptation is not working)

**Comment by Tolu-Mals** [comment]
> Haha works as magic 😅 but its showing dark theme for light mode users by default unless they change it back to light mode manually (system theme adaptation is not working)

Let's try making 'system' default and see if the glitch goes away.

**Comment by Tolu-Mals** [comment]
It works over here, @Royal-lobster @Adebesin-Cell can you confirm that it still works?

**Comment by Adebesin-Cell** [comment]
> It works over here, @Royal-lobster @Adebesin-Cell can you confirm that it still works?

Okay, give me a sec to test.

**Comment by Adebesin-Cell** [comment]
> Haha works as magic 😅 but its showing dark theme for light mode users by default unless they change it back to light mode manually (system theme adaptation is not working)

Ha 😂.

**Comment by Adebesin-Cell** [comment]
> It works over here, @Royal-lobster @Adebesin-Cell can you confirm that it still works?

I think it works fine 👍.

**Comment by Softdev1** [comment]
Yeah,It works fine now, let's retest again once we merge and be sure that stuff doesn't re-occur again. well done @Adebesin-Cell

**Review by Softdev1 — APPROVED** [review]

**Comment by Adebesin-Cell** [comment]
> Yeah,It works fine now, let's retest again once we merge and be sure that stuff doesn't re-occur again. well done @Adebesin-Cell

Sweet 🚀. Yeah, we can get it tested again. Thanks @Softdev1

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
LGTM

**Pull request merged**
