### PR TITLE
Fixes CSS adjustment on mobile

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
Fixes CSS adjustment on mobile

Before:
190167700-c9e4ec29-ec1d-4de5-b374-88c90afe9c86

After:

localhost_4000_search_dece(iPhone 12 Pro) (1)

closes https://github.com/EveripediaNetwork/issues/issues/713

### CODE REVIEW

**Review by Royal-lobster — APPROVED** [review]

**Comment by anubra266** [comment]
@Adebesin-Cell I found out late that @kesar reassigned this issue to you. So I already worked on a PR for the viewport issue, it's been approved and merged.

**Comment by Adebesin-Cell** [comment]
@anubra266 Oh, okay.

**Comment by kesar** [comment]
i guess we can close then, anyhow good work 👍🏻

**Comment by Adebesin-Cell** [comment]
Overflow issue fix

**Comment by Adebesin-Cell** [comment]
Overflow issue fix @anubra266

**Review by anubra266 — APPROVED** [review]

**Pull request merged**
