### PR TITLE
About page redesign

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
About page redesign

closes https://github.com/EveripediaNetwork/issues/issues/1040

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
Text is too small
image
image

frames are too small, and the strokes around them are missing
image

will update some of this in the design too

**Comment by Adebesin-Cell** [comment]
> Text is too small image image
> 
> frames are too small, and the strokes around them are missing image
> 
> will update some of this in the design too

Noted @Simplypheyie96, I'll fix them.

**Comment by Simplypheyie96** [comment]
@Adebesin-Cell I have retouched every element, so please re-inspect and make the changes.

**Comment by Royal-lobster** [comment]
I think this is too big 🤔

CleanShot 2023-02-17 at 16 16 34@2x

**Comment by Adebesin-Cell** [comment]
> I think this is too big 🤔
> 
> CleanShot 2023-02-17 at 16 16 34@2x

Hmm, @Simplypheyie96 ?

**Comment by Simplypheyie96** [comment]
> > I think this is too big 🤔
> > CleanShot 2023-02-17 at 16 16 34@2x
> 
> Hmm, @Simplypheyie96 ?

I'll review it now.

**Comment by Simplypheyie96** [comment]
- Now, this is too compact
image
it looks like this in the design
image

-text in the boxes was not updated
image
- too compact
image
- this wasn't updated too, it should be larger now.
image
- history section is too large and compact too.
they definitely are too big and more compact than the design @Adebesin-Cell

**Comment by Adebesin-Cell** [comment]
Ha! I'll fix them.

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
