### PR TITLE
Updates to Next 13

### PR DESCRIPTION
**Pull request by Royal-lobster**
Fixes https://github.com/EveripediaNetwork/issues/issues/843

# Changes
- Updates Nextjs version to 13
- makes alt tag on images from optional to required
- fixes Image component type for width and height and makes changes to reflect new image component api
- removes edge runtime due to memory limit issue
- fixes type errors in various places
- fixes linkOverlay component not working

### CODE REVIEW

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
image
@Royal-lobster, I don't know if this is a result of the upgrade.

**Comment by Emmanueldmlr** [comment]
image

@Royal-lobster found this too...

**Comment by kesar** [comment]
before merging this, lets make sure we heavily test it and lets run some performance scanners to make sure we dont break anything / we get low google score 👍🏻

**Comment by Royal-lobster** [comment]
> image
> 
> @Royal-lobster, I don't know if this is a result of the upgrade.

Ohh yes, they are not from this branch, but i will add a fix it in this PR.

**Comment by Royal-lobster** [comment]
@Emmanueldmlr added fixes for trending wikis height and overflow issue!

@kesar Works fine on a general outlook over various pages, checked by publishing wiki, editing, checked images from various pages. me and @Softdev1 did lighthouse scans on home, wiki and about page, we didn't find any drastic change but there are no breaking elements we found yet. 

We still have to verify the lighthouse scores after the merge to check the improvements

**Review by Softdev1 — COMMENTED** [review]
so I had a call with @Royal-lobster to test and below is the result of the test.
CleanShot_2022-11-15_at_18 54 462x
CleanShot_2022-11-15_at_18 55 562x
so this is what we concluded that after the merge we would still re-test to double check again

**Comment by kesar** [comment]
result looks a bit worse :/ lets test it a couple of times to see whats the avg scores

**Comment by Softdev1** [comment]
Okay @kesar  I will get it tested again

**Comment by Royal-lobster** [comment]
@kesar on average the tests seems to converge to same, these are the results for some page.

(Left is Next13 and Right is from dev main branch)

CleanShot 2022-11-15 at 20 00 44@2x
CleanShot 2022-11-15 at 20 59 14@2x
CleanShot 2022-11-15 at 21 01 40@2x
CleanShot 2022-11-15 at 21 04 05@2x

but on mobile, the next 13 seems to be consistently. the SEO is low because of indexing disabled

CleanShot 2022-11-15 at 21 20 58@2x

**Comment by kesar** [comment]
cool, so lets give it a try in prod :P

**Comment by kesar** [comment]
yolo

**Pull request merged**
