### PR TITLE
Migrates Wagmi to version 5

### PR DESCRIPTION
**Pull request by Royal-lobster**
Closes https://github.com/EveripediaNetwork/issues/issues/539

Fixes https://github.com/EveripediaNetwork/issues/issues/554

# Changes
- migrated wagmi to version 5
- fixed useAccount and useConnect as per breaking changes
- fixed logout button not appearing due to SSR

### CODE REVIEW

**Comment by kesar** [comment]
wow promising, interface in new wagmi looks much cleaner. let's test it tomorrow morning and if everything works fine we can merge it 👍🏻

**Comment by kesar** [comment]
@Softdev1 test this branch creating wiki and changing user settings to confirm that everything works fine. test w metamask & email login

**Comment by Softdev1** [comment]
@kesar  Okay

**Comment by kesar** [comment]
letss goo

**Pull request merged**
