### PR TITLE
Feat add AI tokens

### PR DESCRIPTION
**Pull request by SidharthK2**
# Add `AI Tokens` tab to rankings table on landing and rank page.

Adds AI token table to ranking table. Existing token data is filtered and rendered in AI tokens tab sorted by market cap.

WIP screenshot

image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/1799

### CODE REVIEW

**Review by Aliiiu — APPROVED** [review]

**Comment by Aliiiu** [comment]
> Details

since we have no data why are we having pagination

**Review by Aliiiu — APPROVED** [review]

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
image

doesn't look good on mobile, you can reduce the size of the icons, the text and the spacing between the tabs @SidharthK2

**Comment by Simplypheyie96** [comment]
> image
> 
> doesn't look good on mobile, you can reduce the size of the icons, the text and the spacing between the tabs @SidharthK2 also, we can make it the default size but the tab scrollable. just like the table so as to not squeeze the tab

image
something like this. so the tab is scrollable too @SidharthK2

**Comment by Simplypheyie96** [comment]
> > > image
> > > doesn't look good on mobile, you can reduce the size of the icons, the text and the spacing between the tabs @SidharthK2 also, we can make it the default size but the tab scrollable. just like the table so as to not squeeze the tab
> > 
> > 
> > image something like this. so the tab is scrollable too @SidharthK2
> 
> @Simplypheyie96 so keep the table as is, and make it side-scrollable?

let's do it that way. so we won't have to squeeze anything

**Review by Simplypheyie96 — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]

**Review by AshakaE — APPROVED** [review]

**Pull request merged**
