### PR TITLE
Fixed mobile nav icon to design

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Fixed mobile nav icon to fit design

_the icons next to the navlabel in the mobile were different to the design on Figma

## How should this be tested?
By checking the mobile vie of the hamburger menu

1. Before

galaxy-note-10-pldryr5yus-6 8-1440 x 3040

2. Now
galaxy-note-10-plus-6 8-1440 x 3040

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/451

### CODE REVIEW

**Review by Softdev1 — APPROVED** [review]
Everything is fine and the errorrs has been corrected

**Comment by Softdev1** [comment]
@OleanjiKingCode  I think you touched the trending wikis, those dots are not there, it should only appear when the wikis is more than three please affect the corrections.

**Comment by OleanjiKingCode** [comment]
> Everything is fine and the errorrs has been corrected

can i merge now?

**Review by kesar — APPROVED** [review]

**Comment by kesar** [comment]
> > Everything is fine and the errorrs has been corrected
> 
> can i merge now?

yess

**Review by codiejay — APPROVED** [review]
lgtm

**Review by anubra266 — APPROVED** [review]

**Pull request merged**
