### PR TITLE
fixed the mobile UI to fit design

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Mobile UI to Design

_This makes the mobile view of the app look to fit the same as in the design

## How should this be tested?
   By checking the design and the mobile view for total similarity and better mobile view
   Design view
image

1. Before Fixing
  
172887986-9deb0190-713b-4357-aa07-0a4314ce774c

2. After fixing
image

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/421

### CODE REVIEW

**Comment by OleanjiKingCode** [comment]
> You don't have to specify the fontSize for the sm since it has the same value as the base. it should be fontSize={{base:20, lg:36}}

done
waiting for other reviewers

**Comment by moraesux** [comment]
I think now the name "NFTs" is now too small. if you notice in the first image, in figma, they are well balanced. Can you increase the size a little to have a comparison?

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
please remove this arrow with a bar from the mobile implementation
image
i'm sorry, gabriel wasn't aware of the fact that i had a discussion with the dev that initially implemented this.
The whole text description should be visible.
Some design decision were discussed in person with the devs. so for each of those pages, the the description texts should be visible.
If you check the design, the bar is not there

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
Well done.
Now, this icon is too small.
IMG_20220614_215404

**Comment by OleanjiKingCode** [comment]
> Well done. Now, this icon is too small. IMG_20220614_215404

this is how it looks now
image

**Comment by Simplypheyie96** [comment]
> Visit Preview

I am previewing on my phone and it is still very tiny. Check the design

**Comment by OleanjiKingCode** [comment]
> > Visit Preview
> 
> I am previewing on my phone and it is still very tiny. Check the design

sorry i would check it... that would be the mobile view

**Review by anubra266 — APPROVED** [review]

**Comment by OleanjiKingCode** [comment]
> > Visit Preview
> 
> I am previewing on my phone and it is still very tiny. Check the design
I think it is tiny on your phone because you are checking the real website I've not merged it so it wont show there

**Comment by Simplypheyie96** [comment]
> > > Visit Preview
> > 
> > 
> > I am previewing on my phone and it is still very tiny. Check the design
> > I think it is tiny on your phone because you are checking the real website I've not merged it so it wont show there

I'm checking on the preview site

**Comment by Simplypheyie96** [comment]
Screenshot_2022-06-16-11-53-01-652_com microsoft emmx
If see the link in the picture above, you'll see that it's the preview link

**Comment by kesar** [comment]
86.9 KB/s ?? what kind of internet is that? :)))

**Comment by Simplypheyie96** [comment]
> 86.9 KB/s ?? what kind of internet is that? :)))
LMAO....
internet connection here is a bit terrible, so is electricity, but we make sure to get things done.

**Comment by OleanjiKingCode** [comment]
> > > > Visit Preview
> > > 
> > > 
> > > I am previewing on my phone and it is still very tiny. Check the design
> > > I think it is tiny on your phone because you are checking the real website I've not merged it so it wont show there
> 
> I'm checking on the preview site

i didnt know about the preview site really sorry i would do it..im also seeing some errors apart from that one

**Comment by OleanjiKingCode** [comment]
> > > > > Visit Preview
> > > > 
> > > > 
> > > > I am previewing on my phone and it is still very tiny. Check the design
> > > > I think it is tiny on your phone because you are checking the real website I've not merged it so it wont show there
> > 
> > 
> > I'm checking on the preview site
> 
> i didnt know about the preview site really sorry i would do it..im also seeing some errors apart from that one

Ive done it now, also i noticed the very small size of the "Everpedia" text and ive adjusted it along with the text bleeding out of the screen

**Review by Simplypheyie96 — APPROVED** [review]
@OleanjiKingCode it looks really good now. Great work.

**Pull request merged**
