### PR TITLE
update: adjusting the design for mobile view

### PR DESCRIPTION
**Pull request by Aliiiu**
# Updating the mobile design for the profile settings page

This PR updates the design and development of the profile settings page to improve the mobile user experience. The changes include:

- [ ] Refactoring the layout to better fit smaller screen sizes and improve overall readability

- [ ] Optimizing the responsive design to ensure a consistent experience across different devices and screen sizes

## How should this be tested?

1. Go to profile settings page
2. Switch to mobile screen

## Notes or observations

image

### CODE REVIEW

**Comment by Dewalz** [comment]
> # Updating the mobile design for the profile settings page
> This PR updates the design and development of the profile settings page to improve the mobile user experience. The changes include:
> 
> * [ ]  Refactoring the layout to better fit smaller screen sizes and improve overall readability
> * [ ]  Optimizing the responsive design to ensure a consistent experience across different devices and screen sizes
> 
> ## How should this be tested?
> 1. Go to profile settings page
> 2. Switch to mobile screen
> 
> ## Notes or observations
> image
> 
> ## Linked issues



> # Updating the mobile design for the profile settings page
> This PR updates the design and development of the profile settings page to improve the mobile user experience. The changes include:
> 
> * [ ]  Refactoring the layout to better fit smaller screen sizes and improve overall readability
> * [ ]  Optimizing the responsive design to ensure a consistent experience across different devices and screen sizes
> 
> ## How should this be tested?
> 1. Go to profile settings page
> 2. Switch to mobile screen
> 
> ## Notes or observations
> image
> 
> ## Linked issues

image
the text "Profile Image" and "profile banner" is supposed to be centered aligned

**Comment by Aliiiu** [comment]
> 
> > image
> > 
> > ## Linked issues
> 
> image
> the text "Profile Image" and "profile banner" is supposed to be centered aligned  @Aliiiu 

For some reasons I still can't add you as a reviewer

**Comment by Aliiiu** [comment]
> > image
> > ## Linked issues
> 
> image the text "Profile Image" and "profile banner" is supposed to be centered aligned @Aliiiu

@Dewalz 

image

**Comment by Softdev1** [comment]
Please ensure you always link PR to the main issue, Please that should be the first thing before once you add reviewer 👍🏻

**Comment by Aliiiu** [comment]
> Please ensure you always link PR to the main issue, Please that should be the first thing before once you add reviewer 👍🏻

The issue was not created, that was the reason why.

**Review by OleanjiKingCode — APPROVED** [review]

**Pull request merged**
