### PR TITLE
More social links and update to React 18

### PR DESCRIPTION
**Pull request by anubra266**
Resolves EveripediaNetwork/issues#294

**NB**: The Social profiles are not yet hooked up to backend, because we have new fields, and I'm not sure the backend is hooked up to accept them yet.

https://user-images.githubusercontent.com/30869823/167744264-dc039a84-9fd6-4437-9471-d3347161cc98.mp4

### CODE REVIEW

**Comment by kesar** [comment]
> NB: The Social profiles are not yet hooked up to backend, because we have new fields, and I'm not sure the backend is hooked up to accept them yet.

You need to add them in the metadata same way that the old twitter one was added 👍🏻

**Review by Simplypheyie96 — COMMENTED** [review]
Implementation looking great. I feel there should be an '@' infront of the usernames for specificity.

**Comment by kesar** [comment]
take in consideration that this might could be called Links instead of social links because there will be stuff like coinmarketcap token or coingecko.. and those dont have @ in front.

it can be an ens domain like kesar.eth or a discord invitation, so it needs to be a bit more generalist 👍🏻

**Comment by Simplypheyie96** [comment]
> take in consideration that this might could be Links instead of social links because there will be stuff like coinmarketcap token or coingecko.. and those dont have @ in front.
> 
> it can be an ens domain like kesar.eth or a discord invitation, so it needs to be a bit more generalist 👍🏻

ohhh. okay.. i understand. i thought it was just for social media.

**Comment by kesar** [comment]
yeah, sorry about the confusion, in my original task I wrote social links, but the list of possible links was broader than just social links 👍🏻

**Comment by anubra266** [comment]
Backend hooked @kesar

**Comment by kesar** [comment]
looking good, lets fix the build so i can test it in vercel 👍🏻

**Comment by anubra266** [comment]
> looking good, lets fix the build so i can test it in vercel 👍🏻

@kesar those components aren't part of my changes. Quite confused bow they're coming in. 😢

**Comment by kesar** [comment]
> > looking good, lets fix the build so i can test it in vercel 👍🏻
> 
> @kesar those components aren't part of my changes. Quite confused bow they're coming in. 😢

Type 'React.ReactNode' is not assignable to type 'import("/vercel/path0/node_modules/@zag-js/dom-utils/node_modules/@types/react/index").ReactNode

it might be related to the zag-js import and some conflict

**Comment by anubra266** [comment]
@kesar turns out to be a React18 issue, the zag project uses react 18

**Review by kesar — APPROVED** [review]

**Pull request merged**
