### PR TITLE
Fixes rank page itr

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
Fixes rank page itr

fixes https://github.com/EveripediaNetwork/issues/issues/1033

### CODE REVIEW

**Comment by Adebesin-Cell** [comment]
Screenshots:

localhost_4000_wiki_super-bowl-lvii-nfts
localhost_4000_ (7)

**Comment by Adebesin-Cell** [comment]
Screen Shot 2023-02-11 at 12 24 29 AM

With tooltip, I think for interactions a PopOver will be better @Simplypheyie96 @Royal-lobster.

**Comment by Royal-lobster** [comment]
> Screen Shot 2023-02-11 at 12 24 29 AM
> 
> With tooltip, I think for interactions a PopOver will be better @Simplypheyie96 @Royal-lobster.

Hmm, I think maybe after more than 3 founders the flex direction column would look good with all founders visible.

**Comment by Adebesin-Cell** [comment]
> 

You mean on the value part of the founders, row or column?

**Review by Softdev1 — APPROVED** [review]
this is alot better now

**Comment by Softdev1** [comment]
for the single founders like BUSD founder  and Cardano founder remove the comma at the end of their name

**Comment by Royal-lobster** [comment]
> > 
> 
> You mean on the value part of the founders, row or column?


Something like this

CleanShot 2023-02-11 at 17 02 24@2x

```js
flexDirection={founders.length > 3 ? "column": "row"}
```

**Comment by kesar** [comment]
> Screenshots:
> 
> localhost_4000_wiki_super-bowl-lvii-nfts Screen Shot 2023-02-10 at 6 35 31 PM

we should support up to two lines of founders. that would make that most of the founders will fit and it shouldnt increase the row height since we already have a column with 2 rows ( tokens column )

**Comment by Adebesin-Cell** [comment]
> > > 
> > 
> > 
> > You mean on the value part of the founders, row or column?
> 
> Something like this
> 
> CleanShot 2023-02-11 at 17 02 24@2x
> 
> ```js
> flexDirection={founders.length > 3 ? "column": "row"}
> ```
> 
> In think case we don't need to hide founders in separate popups and the container can still grow vertically

Screen Shot 2023-02-11 at 1 22 17 PM
Fixed...

**Comment by Royal-lobster** [comment]
> Screen Shot 2023-02-11 at 1 25 11 PM
> 
> Fixed.

I am thinking something like this :

when there are more than 3 :

CleanShot 2023-02-11 at 18 08 44@2x

when there are less than 3 :

CleanShot 2023-02-11 at 18 13 23@2x

**Comment by Adebesin-Cell** [comment]
> > Screen Shot 2023-02-11 at 1 25 11 PM
> > Fixed.
> 
> I am thinking something like this :
> 
> when there are more than 3 :
> 
> CleanShot 2023-02-11 at 18 08 44@2x
> 
> when there are less than 3 :
> 
> CleanShot 2023-02-11 at 18 13 23@2x

Oh! This looks much better, I’ll fix that.

**Comment by Adebesin-Cell** [comment]
Screen Shot 2023-02-11 at 2 49 39 PM
@Royal-lobster @Simplypheyie96

**Comment by Royal-lobster** [comment]
Cool. This is much better !

**Review by Royal-lobster — APPROVED** [review]

**Comment by kesar** [comment]
pls fix conflicts and merge

**Pull request merged**
