### PR TITLE
Fix account rounting

### PR DESCRIPTION
**Pull request by Emmanueldmlr**
# Improper Routing of the setting page

_As a Developer, I need to ensure that the settings page is properly routed, so that users can easily navigate to and modify their preferences.

fixes https://github.com/EveripediaNetwork/issues/issues/1189

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@Softdev1, we need to test this update aggressively just to be sure nothing breaks.

**Comment by Softdev1** [comment]
sure we would ensure nothing breaks via careful and precise testing @Emmanueldmlr

**Comment by kesar** [comment]
why u didnt move the /settings path that has only 1 or 2 links ? we can't replace route of accounts that will affect to SEO

**Comment by Emmanueldmlr** [comment]
oops. I was much more particular about the URL. I will rework it now.

**Comment by kesar** [comment]
yeah i think that would work better 👍🏻 👍🏻  thx!

**Review by Softdev1 — APPROVED** [review]
Tested and it is working fine.

**Pull request merged**
