### PR TITLE
translate chat bot

### PR DESCRIPTION
**Pull request by Tolu-Mals**
# Summary

Closes https://github.com/EveripediaNetwork/issues/issues/2154. Translates the chat bot UI

### Screenshot

Screenshot 2024-01-09 at 3 11 22 PM

### CODE REVIEW

**Comment by SidharthK2** [comment]
image

On minimizing chat

**Review by SidharthK2 — COMMENTED** [review]
image

On minimizing chat

**Comment by Tolu-Mals** [comment]
> image
> 
> On minimizing chat

oh nice catch

**Comment by Tolu-Mals** [comment]
> image
> 
> On minimizing chat

fixed

**Pull request merged**
