### PR TITLE
Wiki Quality Score

### PR DESCRIPTION
**Pull request by Royal-lobster**
Closes https://github.com/EveripediaNetwork/issues/issues/508

# Changes
- implemented wiki score logic as per pseudocode 
- saving wiki score to wiki metadata
- added wiki score indicator to editor to show live score changes
- added tooltip on wiki score indicator for more info

# Links
- https://monopedia-ui-git-wiki-score-prediqt.vercel.app/create-wiki?slug=sushiswap

# Screenshots

https://user-images.githubusercontent.com/52039218/181100021-caa5c18f-650e-4da7-9e47-47df84b51a6b.mp4

### CODE REVIEW

**Comment by Simplypheyie96** [comment]
Great job @Royal-lobster ... as always.. 
i think we should increase the size of the text in the progress bar. it's currently 8px.  I changed it to 12px on figma. The number is barely visible.

**Comment by Royal-lobster** [comment]
> Great job @Royal-lobster ... as always.. i think we should increase the size of the text in the progress bar. it's currently 8px. I changed it to 12px on figma. The number is barely visible.

Ohh that's true. i will make the change.

**Comment by Royal-lobster** [comment]
@Simplypheyie96 now it looks like this
CleanShot 2022-07-27 at 01 53 59@2x

**Comment by Simplypheyie96** [comment]
looks a lot better now

**Review by Simplypheyie96 — APPROVED** [review]

**Review by OleanjiKingCode — APPROVED** [review]

**Review by kesar — APPROVED** [review]
awesome PR

**Pull request merged**
