### PR TITLE
feat/blog

### PR DESCRIPTION
**Pull request by JustinCast**
# Blog implementation
_Consume mirror.xyz api to show blogs created by a particular addr_

## How should this be tested?
- Using the attached link

## Linked issues
closes https://github.com/EveripediaNetwork/issues/issues/572

### CODE REVIEW

**Comment by Emmanueldmlr** [comment]
@JustinCast , is there a link to where I can test the update?

**Comment by JustinCast** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Updated
> **monopedia-ui**	✅ Ready ([Inspect](https://vercel.com/prediqt/monopedia-ui/CX1mdMMsvN7nx1Xa36AcqkpZM6Lz))	[Visit Preview](https://monopedia-ui-git-feat-blog-prediqt.vercel.app)	Aug 15, 2022 at 8:51PM (UTC)

@Emmanueldmlr you can use this link

**Comment by Emmanueldmlr** [comment]
I meant the link to the specific page you worked on

**Comment by JustinCast** [comment]
> @JustinCast , is there a link to where I can test the update?

You can use https://monopedia-ui-git-feat-blog-prediqt.vercel.app/blog

**Review by anubra266 — APPROVED** [review]

**Review by Royal-lobster — APPROVED** [review]

**Comment by kesar** [comment]
few comments: ( not sure if needs to update figma / discuss but tagging also @Simplypheyie96 just in case ) / @JustinCast 

https://monopedia-ui-git-feat-blog-prediqt.vercel.app/blog

- title has more margins than other pages like activity, lets make sure we have same in ALL pages.

- in blog cards font size of date looks pretty big, its also aligned to left when its right aligned everywhere in the site ( wiki cards, activity page)

https://monopedia-ui-git-feat-blog-prediqt.vercel.app/blog/LNeXtYYEF_mkbFZDano3tInGeo5tDr57L3c8NyzCq9E

- title has too much top margin

- left and right margins on blog seems to narrow, why that? for example activity page its wider. (checked on laptop)

- missing SEO headers

- links in pink, to follow same standard across the whole site

- if you access to a wiki, there is not a way to go back

- too many suggested wikis. 4 should be fine.

**Comment by Simplypheyie96** [comment]
@kesar This task was assigned to gabriel, I'll assign to him changes he needs to make on the design. 
On figma, the font size of date is pretty much the same as on every other wiki card, but it is left aligned because it doesn't contain the blog writer since it is a blog for the website. And I think it is fine for the blog card to be different from the wiki cards since they aren't the same, it'll help users differentiate between them.

Agree on every other point made. infact, I think 3 blog post is fine for the suggested blogs.

**Comment by JustinCast** [comment]
> few comments: ( not sure if needs to update figma / discuss but tagging also @Simplypheyie96 just in case ) / @JustinCast
> 
> https://monopedia-ui-git-feat-blog-prediqt.vercel.app/blog
> 
> * title has more margins than other pages like activity, lets make sure we have same in ALL pages.
> * in blog cards font size of date looks pretty big
> 
> https://monopedia-ui-git-feat-blog-prediqt.vercel.app/blog/LNeXtYYEF_mkbFZDano3tInGeo5tDr57L3c8NyzCq9E
> 
> * title has too much top margin
> * left and right margins on blog seems to narrow, why that? for example activity page its wider. (checked on laptop)
> * missing SEO headers
> * links in pink, to follow same standard across the whole site
> * if you access to a wiki, there is not a way to go back
> * too many suggested wikis. 4 should be fine.

I think this is fixed now!

**Review by kesar — APPROVED** [review]

**Pull request merged**
