### PR TITLE
Makes blog generate on static revalidation

### PR DESCRIPTION
**Pull request by Royal-lobster**
Fixes https://github.com/EveripediaNetwork/issues/issues/970

# Changes
- changes getServerSideProps to getStaticProps on blog page

### CODE REVIEW

**Comment by kesar** [comment]
i think we would need some kind of revalidation

https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-pages

perhaps revalidate each 5 min.

**Comment by Royal-lobster** [comment]
> i think we would need some kind of revalidation
> 
> [nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-pages](https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-pages)
> 
> perhaps revalidate each 5 min.

Yes ! I am thinking we might do the same as we are doing for wiki pages, we can revalidate pages with web-hook, i am investigating if mirror has web hook feature on publish

**Comment by Royal-lobster** [comment]
@kesar seems like there is no web hooks integration on mirror.xyz :( so added the 5 min revalidation instead.

**Review by Emmanueldmlr — APPROVED** [review]

**Comment by Emmanueldmlr** [comment]
@Royal-lobster , still a WIP?

**Comment by Royal-lobster** [comment]
> @Royal-lobster , still a WIP?

Nope 😅 forgot to remove from draft

**Review by kesar — APPROVED** [review]

**Pull request merged**
