### PR TITLE
changed the banner of the categories

### PR DESCRIPTION
**Pull request by OleanjiKingCode**
# Explore and Ctegores page bannners

_Fixed the explore page to how requested by @Simplypheyie96  and changed the banners of the categories

## How should this be tested?

1. ## This is how the explore page and the banners of the categories look before

image

Screenshot (294)

Screenshot (295)

Screenshot (296)

Screenshot (297)

Screenshot (298)

Screenshot (299)

2. ## Now
Screenshot (293)
Screenshot (300)
Screenshot (301)
Screenshot (302)
Screenshot (303)
Screenshot (304)
Screenshot (305)

## Linked issues

closes https://github.com/EveripediaNetwork/issues/issues/504

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
this isn't what i asked to be changed 🥲
The link I sent is the only page I asked for changes and it's the only one not done.
The banner is still the same. I said to change the copy and not to remove the copy.
and I said to remove the (trending wikis in this category text and it is still there

**Comment by OleanjiKingCode** [comment]
> this isn't what i asked to be changed 🥲 The link I sent is the only page I asked for changes and it's the only one not done. The banner is still the same. I said to change the copy and not to remove the copy. and I said to remove the (trending wikis in this category text and it is still there

okay @Simplypheyie96 

- [ ] ive removed the dummy text
- [ ] ive remove the arrow and the trending wikis text 
- [ ] it remains the banner

is it only the banner that remains

> banner changes are from other issue 👍🏻

yes sir

**Comment by Simplypheyie96** [comment]
@OleanjiKingCode it should look like this now since the banner is not ready.

image

**Comment by OleanjiKingCode** [comment]
> @OleanjiKingCode it should look like this now since the banner is not ready.
> 
> image

okay this is what i needed okay ill do this now and for the wiki cards no need to change them

**Comment by Simplypheyie96** [comment]
> > @OleanjiKingCode it should look like this now since the banner is not ready.
> > image
> 
> okay this is what i needed okay ill do this now and for the wiki cards no need to change them

noo.. leave the wiki cards.

**Comment by Simplypheyie96** [comment]
@OleanjiKingCode typo and punctuation alert!
image

**Comment by OleanjiKingCode** [comment]
> @OleanjiKingCode typo and punctuation alert! the text says : Explore different wikis in different categories on Everipedia, Ranging from NFTs, to DAOs and so on. image

Done @Simplypheyie96

**Review by Simplypheyie96 — APPROVED** [review]
It looks good. well done. @OleanjiKingCode

**Pull request merged**
