### PR TITLE
Login rework

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
# Login rework

This PR removes wagmi wrapper to improve performance and utilized better auth system using cookies and verification using signer.

Changes
- [x] Refactored useFetchWalletBalance
- [x] Reworked isAuthentciatedRoute and login page
- [x] Refactored useWeb3Token
- [x] changed rpc url as the initial one won't load up.

## Linked issues

Fixes https://github.com/EveripediaNetwork/issues/issues/2221

### CODE REVIEW

**Comment by Royal-lobster** [comment]
@Softdev1 Share the preview link with editors and see if the switch model issue is solved with this PR

**Review by Aliiiu — COMMENTED** [review]
The Profile Drawer is not working

**Comment by Adebesin-Cell** [comment]
> The Profile Drawer is not working

Screenshot 2024-03-01 at 10 04 21 AM
It works :))

**Review by Royal-lobster — APPROVED** [review]

**Review by SidharthK2 — COMMENTED** [review]
image
I disconnected my wallet but I'm still shown logged in, even on refresh.

**Comment by Adebesin-Cell** [comment]
> image
> I disconnected my wallet but I'm still shown logged in, even on refresh.

Weird, I’ll look into it.

**Comment by SidharthK2** [comment]
> > image
> > I disconnected my wallet but I'm still shown logged in, even on refresh.
> 
> Weird, I’ll look into it.

https://wagmi.sh/react/api/hooks/useAccount#isconnecting-isreconnecting-isconnected-isdisconnected
Probably this is missing

**Comment by Adebesin-Cell** [comment]
> > > image
> > > I disconnected my wallet but I'm still shown logged in, even on refresh.
> > 
> > 
> > Weird, I’ll look into it.
> 
> https://wagmi.sh/react/api/hooks/useAccount#isconnecting-isreconnecting-isconnected-isdisconnected Probably this is missing

I removed wagmi from the wrapper so we can’t use its hook, I prolly missed sth. I’ll check :)) good catch 👏

**Review by Aliiiu — APPROVED** [review]

**Pull request merged**
