### PR TITLE
About page(Team Section)

### PR DESCRIPTION
**Pull request by Damola18**
# About page(Team Section)

This PR updates the profile images for the About page team section and updates copy.

Before 

image

After

image

closes https://github.com/EveripediaNetwork/issues/issues/3064

### CODE REVIEW

**Review by Simplypheyie96 — CHANGES_REQUESTED** [review]
- This is what i meant by checking the breakpoints. The upper part of the image is cut off. Let's update this.
image
image

**Comment by Damola18** [comment]
> Most of the images have been updated, we could also update these two too if possible, they look pixelated
> 
> Screenshot 2024-08-20 at 11 11 39 AM

Yeah, this was based on the quality of the images but will try as much to improve that.

**Comment by Simplypheyie96** [comment]
> Most of the images have been updated, we could also update these two too if possible, they look pixelated

These two is exactly the pictures provided on dropbox. Little to do on that front.

**Comment by Damola18** [comment]
> * This is what i meant by checking the breakpoints. The upper part of the image is cut off. Let's update this.
> 
> image image

Yeah, we can have that changed on the design for all breakpoints. Will replace them now

**Comment by invisiblemask** [comment]
> > Most of the images have been updated, we could also update these two too if possible, they look pixelated
> 
> These two is exactly the pictures provided on dropbox. Little to do on that front.

Oh okay, maybe reducing the size could help?

**Review by invisiblemask — APPROVED** [review]
It looks better now

**Review by Simplypheyie96 — APPROVED** [review]

**Pull request merged**
