### PR TITLE
Add uniswap widget

### PR DESCRIPTION
**Pull request by anubra266**
Resolves EveripediaNetwork/issues#248

CleanShot 2022-04-21 at 09 28 23@2x

### CODE REVIEW

**Comment by kesar** [comment]
really promising! two things

could we make border radius a bit more similar to the ones that we have in the app, that way it will look even more integrated.


somehow we need to be able to reuse the connection we already have w our login system, I logged in w my metamask account but widget is not catching it, so I am not able to use it. That's probably the more complex part, but without that, widget wont be operative.

**Comment by kesar** [comment]
i think its the provider: https://github.com/EveripediaNetwork/ep-ui/pull/185/files#diff-2a119dc424cd23f948ec46d44036cd70a66a64bbfcfcdebecc7dae53f5621c40R19

instead of uniswap provider, i think you need to use the wagmi provider: 

https://wagmi.sh/docs/hooks/useProvider

**Comment by anubra266** [comment]
> i think its the provider: https://github.com/EveripediaNetwork/ep-ui/pull/185/files#diff-2a119dc424cd23f948ec46d44036cd70a66a64bbfcfcdebecc7dae53f5621c40R19
> 
> instead of uniswap provider, i think you need to use the wagmi provider:
> 
> https://wagmi.sh/docs/hooks/useProvider

@kesar I'm actually using wagmi provider, I'm importing it from `_app.tsx`. I only gave it a variable name of `uniswapProvider`

**Comment by kesar** [comment]
you need to use useProvider to get the current hooked one I think that its in the context

**Comment by anubra266** [comment]
> you need to use useProvider to get the current hooked one I think that its in the context

@kesar just tried it. Didn't change anything. 😢

**Comment by kesar** [comment]
perhaps you need to re-render component once provider change / its logged in.

another option it could be use something like https://wagmi.sh/docs/hooks/useConnect and wait till its connected to re-render / pass the provider again.

if none of those work, they have a discord channel for support: https://discord.com/channels/597638925346930701/941447445844463676


as this is something new, we could be hitting some bug

**Comment by anubra266** [comment]
> perhaps you need to re-render component once provider change / its logged in.
> 
> another option it could be use something like https://wagmi.sh/docs/hooks/useConnect and wait till its connected to re-render / pass the provider again.
> 
> if none of those work, they have a discord channel for support: https://discord.com/channels/597638925346930701/941447445844463676
> 
> as this is something new, we could be hitting some bug

@kesar found this in their docs
CleanShot 2022-04-21 at 10 10 09@2x

I'll look for help in their discord though

**Comment by kesar** [comment]
> > perhaps you need to re-render component once provider change / its logged in.
> > another option it could be use something like https://wagmi.sh/docs/hooks/useConnect and wait till its connected to re-render / pass the provider again.
> > if none of those work, they have a discord channel for support: https://discord.com/channels/597638925346930701/941447445844463676
> > as this is something new, we could be hitting some bug
> 
> @kesar found this in their docs CleanShot 2022-04-21 at 10 10 09@2x
> 
> I'll look for help in their discord though

mmm then it could be that we are using matic network on the site but in the rpc we are pointing to ethereum network

**Comment by anubra266** [comment]
@kesar that discord link didn’t help though. 😁 
CleanShot 2022-04-21 at 10 15 39@2x

**Comment by kesar** [comment]
> @kesar that discord link didn’t help though. 😁 CleanShot 2022-04-21 at 10 15 39@2x

https://discord.com/invite/FCfyBSbCU5

they have then a wrong link in the docs :D

**Comment by anubra266** [comment]
@kesar I now get this.
CleanShot 2022-04-21 at 11 15 41@2x

But the wallet seems to be conected

**Pull request closed without merging**
