### PR TITLE
fix language switch bug

### PR DESCRIPTION
**Pull request by Tolu-Mals**
# Summary
Fixes bug where language switch shows wrong language

## How should this be tested?
1. type the language directly in the URL for example: iq.wiki/ko
2. Check to see the language switch selected language corresponds with the language being used

Closes https://github.com/EveripediaNetwork/issues/issues/2306

### CODE REVIEW

**Review by SidharthK2 — COMMENTED** [review]
Unable to switch back to EN from KO by editing URL

**Comment by Aliiiu** [comment]
> Unable to switch back to EN from KO by editing URL

I was able to by removing the "/ko"

**Comment by Aliiiu** [comment]
image

@Tolu-Mals

**Comment by SidharthK2** [comment]
image

**Comment by Tolu-Mals** [comment]
> image @Tolu-Mals

Kindly share the steps to reproduce this

**Comment by Aliiiu** [comment]
> > image @Tolu-Mals
> 
> Kindly share the steps to reproduce this

after adding "/ko" to the url. Then remove it to go back to en translation. The selector locale state does not change between those two state

**Comment by Aliiiu** [comment]
> @Aliiiu @SidharthK2 can you check again, should be fixed now

The behavior is different, now i can switch from en to ko but i can't switch from ko to en by editing the url. When i try to switch from ko to en from the url it keeps persisting the ko lang

**Pull request merged**
