### PR TITLE
Updating FAQ text

### PR DESCRIPTION
**Pull request by codiejay**
Faq update with content from [here](https://docs.google.com/document/d/1QAd8TIa4JkIqE28yui2LIaEJEz_RpdzS54szqnGQsuo/edit)

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/800

### CODE REVIEW

**Review by Softdev1 — APPROVED** [review]

**Review by kesar — CHANGES_REQUESTED** [review]
I thought we discussed in DM that we wouldnt use intl (translations). I am not sure if you can hook html links, lists and so on as its in the document shared.

consider changing this to avoid using intl files, that would make load those chunks of texts in every single page instead of only when someone visit faq

**Comment by kesar** [comment]
please @Softdev1 review carefully pull request because we need to have some basic standards of quality and @codiejay please dont cut corners.

Captura de Pantalla 2022-10-10 a las 16 11 22

Captura de Pantalla 2022-10-10 a las 16 11 16

**Comment by Softdev1** [comment]
Okay I understand @kesar

**Comment by kesar** [comment]
thx 🙏🏻

**Review by kesar — APPROVED** [review]

**Pull request merged**
