### PR TITLE
Improve speed

### PR DESCRIPTION
**Pull request by anubra266**
EveripediaNetwork/issues/481

### CODE REVIEW

**Review by Softdev1 — CHANGES_REQUESTED** [review]
awesome job @anubra266  but I think it could be increased more especially on the mobile view to be precise, the desktop version is getting more improved but can still be improved upon also.
 I will be attaching my screenshot of the test I carried out: 
 
Screenshot (419)](https://user-images.githubusercontent.com/32770520/178452440-51c400a3-ce10-4b35-822b-8e61c4fc9b66.png)
f-4f9d-a22f-a3b321151815.png)

**Comment by anubra266** [comment]
Yes @Softdev1, but I beleive we'll need to merge to see the actual test results. The preview generated for pull requests are naturally slower and less performant than the actual stuff. It's that way to save resources.

**Comment by anubra266** [comment]
Also...I don't expect that this will solve the issue completely. It's just an improvement; so we can know what area to focus on for more improvements

**Review by Softdev1 — COMMENTED** [review]
let's keep improving on it

**Review by kesar — APPROVED** [review]

**Review by Softdev1 — APPROVED** [review]
we are good

**Pull request merged**
