### PR TITLE
fixes switch chain in magic

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
# fixes switch chain in magic

This PR adds switch chain function to magic connector

Fixes

### CODE REVIEW

**Review by Royal-lobster — APPROVED** [review]
@Adebesin-Cell Lets share the preview link to editors and get it tested before merge

**Comment by Adebesin-Cell** [comment]
> @Adebesin-Cell Lets share the preview link to editors and get it tested before merge

I still need to fix some weird error from the method call.

An error occurred when attempting to switch chain. Details: Magic RPC Error: [-32603] Internal error: Unsupported method: wallet_switchEthereumChain. See available methods at https://docs.alchemy.com/alchemy/documentation/apis Version: viem@2.8.13

not sure why ``wallet_switchEthereumChain`` doesn't get support :)), I'll try to use switchChain from wagmi/core hook and see if that fixes it.

**Comment by Adebesin-Cell** [comment]
> > @Adebesin-Cell Lets share the preview link to editors and get it tested before merge
> 
> I still need to fix some weird error from the method call.
> 
> An error occurred when attempting to switch chain. Details: Magic RPC Error: [-32603] Internal error: Unsupported method: wallet_switchEthereumChain. See available methods at [docs.alchemy.com/alchemy/documentation/apis](https://docs.alchemy.com/alchemy/documentation/apis) Version: viem@2.8.13
> 
> not sure why `wallet_switchEthereumChain` doesn't get support :)), I'll try to use switchChain from wagmi/core hook and see if that fixes it.

It's kind of related to the initial issue from switch network bug we had before from one of the editors were add_ethereumChain wasn't supported.

**Comment by Royal-lobster** [comment]
> > @Adebesin-Cell Lets share the preview link to editors and get it tested before merge
> 
> I still need to fix some weird error from the method call.
> 
> An error occurred when attempting to switch chain. Details: Magic RPC Error: [-32603] Internal error: Unsupported method: wallet_switchEthereumChain. See available methods at [docs.alchemy.com/alchemy/documentation/apis](https://docs.alchemy.com/alchemy/documentation/apis) Version: viem@2.8.13
> 
> not sure why `wallet_switchEthereumChain` doesn't get support :)), I'll try to use switchChain from wagmi/core hook and see if that fixes it.

Ahh 😅I tried to search in their docs on how to switch the chain, but it looks like there is no info on their docs, i think the best for us would be to directly ask from their discord. see if you can get someone to help

**Comment by Adebesin-Cell** [comment]
> > > @Adebesin-Cell Lets share the preview link to editors and get it tested before merge
> > 
> > 
> > I still need to fix some weird error from the method call.
> > An error occurred when attempting to switch chain. Details: Magic RPC Error: [-32603] Internal error: Unsupported method: wallet_switchEthereumChain. See available methods at [docs.alchemy.com/alchemy/documentation/apis](https://docs.alchemy.com/alchemy/documentation/apis) Version: viem@2.8.13
> > not sure why `wallet_switchEthereumChain` doesn't get support :)), I'll try to use switchChain from wagmi/core hook and see if that fixes it.
> 
> Ahh 😅I tried to search in their docs on how to switch the chain, but it looks like there is no info on their docs, i think the best for us would be to directly ask from their discord. see if you can get someone to help

Yep! I checked the documentation as well, didn't help with any solution or guide on how to switch chains. I'll try discord but that's if we get a faster response, do you happen to have their discord link?
I'll test with switchChainAsync that was the work around I used for the create wiki switch network.

**Comment by Adebesin-Cell** [comment]
> > > > @Adebesin-Cell Lets share the preview link to editors and get it tested before merge
> > > 
> > > 
> > > I still need to fix some weird error from the method call.
> > > An error occurred when attempting to switch chain. Details: Magic RPC Error: [-32603] Internal error: Unsupported method: wallet_switchEthereumChain. See available methods at [docs.alchemy.com/alchemy/documentation/apis](https://docs.alchemy.com/alchemy/documentation/apis) Version: viem@2.8.13
> > > not sure why `wallet_switchEthereumChain` doesn't get support :)), I'll try to use switchChain from wagmi/core hook and see if that fixes it.
> > 
> > 
> > Ahh 😅I tried to search in their docs on how to switch the chain, but it looks like there is no info on their docs, i think the best for us would be to directly ask from their discord. see if you can get someone to help
> 
> Yep! I checked the documentation as well, didn't help with any solution or guide on how to switch chains. I'll try discord but that's if we get a faster response, do you happen to have their discord link? I'll test with switchChainAsync that was the work around I used for the create wiki switch network.

Same errors, and looking at other connectors that switch chain works with from wagmi.
https://github.com/wevm/wagmi/blob/main/packages/connectors/src/walletConnect.ts
https://github.com/wevm/wagmi/blob/main/packages/connectors/src/metaMask.ts
https://github.com/wevm/wagmi/blob/main/packages/connectors/src/coinbaseWallet.ts

They use the same methods, not sure why it's failing here

**Review by SidharthK2 — APPROVED** [review]

**Pull request closed without merging**
