### PR TITLE
Fix/profile

### PR DESCRIPTION
**Pull request by anubra266**
Resolves EveripediaNetwork/issues/issues#179

https://user-images.githubusercontent.com/30869823/160001641-42b8e7bb-fd77-40f2-a92c-29c7a6ddc16b.mp4

### CODE REVIEW

**Comment by kesar** [comment]
checking from phone but i think its missing the navbar w proper link to profile 👍

**Comment by anubra266** [comment]
Fixed @kesar

**Comment by kesar** [comment]
missing mobile navbar version

**Comment by kesar** [comment]
btw love the video in the description 👍🏻  great work!

**Review by kesar — CHANGES_REQUESTED** [review]
- navbar for mobile

- if you are not logged in, link of profile on navbar goes to undefined. It should go to login as an authenticated route

**Review by kesar — APPROVED** [review]

**Pull request merged**
